In [1]:
import pandas as pd
import numpy as np

In [2]:
sales = pd.read_csv(
    "../data/raw/sales_train_validation.csv",
    nrows=1000
)
calendar = pd.read_csv(
    "../data/raw/calendar.csv"
)
prices = pd.read_csv(
    "../data/raw/sell_prices.csv"
)

In [3]:
print("Sales:", sales.shape)
print("Calendar:", calendar.shape)
print("Prices:", prices.shape)

Sales: (1000, 1919)
Calendar: (1969, 14)
Prices: (6841121, 4)

In [4]:
#identify identifier and sales columns
id_cols=["id","item_id","dept_id","cat_id","store_id","state_id"]

sales_cols =[
    col for col in sales.columns
    if col.startswith("d_")
]
print("Number of sales columns:",len(sales_cols))
print(sales_cols[:10])

Number of sales columns: 1913
['d_1', 'd_2', 'd_3', 'd_4', 'd_5', 'd_6', 'd_7', 'd_8', 'd_9', 'd_10']

In [15]:
# for changing the format from wide range to long we will use melt
sales_long=sales.melt(
    id_vars=id_cols,
    value_vars=sales_cols,
    var_name="d",
    value_name="sales"
)
sales_long.tail()

,id,item_id,dept_id,cat_id,store_id,state_id,d,sales
1912995,HOUSEHOLD_1_440_CA_1_validation,HOUSEHOLD_1_440,HOUSEHOLD_1,HOUSEHOLD,CA_1,CA,d_1913,1
1912996,HOUSEHOLD_1_441_CA_1_validation,HOUSEHOLD_1_441,HOUSEHOLD_1,HOUSEHOLD,CA_1,CA,d_1913,5
1912997,HOUSEHOLD_1_442_CA_1_validation,HOUSEHOLD_1_442,HOUSEHOLD_1,HOUSEHOLD,CA_1,CA,d_1913,0
1912998,HOUSEHOLD_1_443_CA_1_validation,HOUSEHOLD_1_443,HOUSEHOLD_1,HOUSEHOLD,CA_1,CA,d_1913,0
1912999,HOUSEHOLD_1_444_CA_1_validation,HOUSEHOLD_1_444,HOUSEHOLD_1,HOUSEHOLD,CA_1,CA,d_1913,0

In [16]:
sales_long.shape

(1913000, 8)

In [17]:
# now we use the calendar dataframe
#first we will inspect thsi
calendar[["d","date"]]

           d        date
0        d_1  2011-01-29
1        d_2  2011-01-30
2        d_3  2011-01-31
3        d_4  2011-02-01
4        d_5  2011-02-02
...      ...         ...
1964  d_1965  2016-06-15
1965  d_1966  2016-06-16
1966  d_1967  2016-06-17
1967  d_1968  2016-06-18
1968  d_1969  2016-06-19

[1969 rows x 2 columns]

In [18]:
sales_long=sales_long.merge(
    calendar[["d","date"]],
    on="d",
    how="left"
)
sales_long.head()

,id,item_id,dept_id,cat_id,store_id,state_id,d,sales,date
0,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29
1,HOBBIES_1_002_CA_1_validation,HOBBIES_1_002,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29
2,HOBBIES_1_003_CA_1_validation,HOBBIES_1_003,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29
3,HOBBIES_1_004_CA_1_validation,HOBBIES_1_004,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29
4,HOBBIES_1_005_CA_1_validation,HOBBIES_1_005,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29

In [19]:
sales_long.shape

(1913000, 9)

In [20]:
sales_long["date"]=pd.to_datetime(sales_long["date"])

In [22]:
sales_long.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1913000 entries, 0 to 1912999
Data columns (total 9 columns):
 #   Column    Dtype
---  ------    -----
 0   id        object
 1   item_id   object
 2   dept_id   object
 3   cat_id    object
 4   store_id  object
 5   state_id  object
 6   d         object
 7   sales     int64
 8   date      datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(7)
memory usage: 131.4+ MB

Now before moving forward we should verify that we merged our dataset correctly and the following points
wide -> long
d_1,d_2 are preserved
calendar dataframe successfully mapped 
Actual dates available 
No unexpected missing values

In [24]:
print(sales_long.shape)
print(sales_long[["item_id", "store_id", "d", "date", "sales"]].head(10))
print(sales_long["date"].min())#minimum date or starting date 
print(sales_long["date"].max())
print(sales_long["sales"].isna().sum())
print(sales_long["date"].isna().sum())

(1913000, 9)
         item_id store_id    d       date  sales
0  HOBBIES_1_001     CA_1  d_1 2011-01-29      0
1  HOBBIES_1_002     CA_1  d_1 2011-01-29      0
2  HOBBIES_1_003     CA_1  d_1 2011-01-29      0
3  HOBBIES_1_004     CA_1  d_1 2011-01-29      0
4  HOBBIES_1_005     CA_1  d_1 2011-01-29      0
5  HOBBIES_1_006     CA_1  d_1 2011-01-29      0
6  HOBBIES_1_007     CA_1  d_1 2011-01-29      0
7  HOBBIES_1_008     CA_1  d_1 2011-01-29     12
8  HOBBIES_1_009     CA_1  d_1 2011-01-29      2
9  HOBBIES_1_010     CA_1  d_1 2011-01-29      0
2011-01-29 00:00:00
2016-04-24 00:00:00
0
0

In [25]:
# d_1 ->2011-01--29 lets check another day
sales_long[sales_long["d"]=="d_2"][["item_id", "store_id", "d", "date", "sales"]
].head()

            item_id store_id    d       date  sales
1000  HOBBIES_1_001     CA_1  d_2 2011-01-30      0
1001  HOBBIES_1_002     CA_1  d_2 2011-01-30      0
1002  HOBBIES_1_003     CA_1  d_2 2011-01-30      0
1003  HOBBIES_1_004     CA_1  d_2 2011-01-30      0
1004  HOBBIES_1_005     CA_1  d_2 2011-01-30      0