In [1]:
import pandas as pd
import numpy as np

In [2]:
sales = pd.read_csv(
    "../data/raw/sales_train_validation.csv"
)
calendar = pd.read_csv(
    "../data/raw/calendar.csv"
)
prices = pd.read_csv(
    "../data/raw/sell_prices.csv"
)

In [3]:
print("Sales:", sales.shape)
print("Calendar:", calendar.shape)
print("Prices:", prices.shape)

Sales: (30490, 1919)
Calendar: (1969, 14)
Prices: (6841121, 4)

In [4]:
#identify identifier and sales columns
id_cols=["id","item_id","dept_id","cat_id","store_id","state_id"]

sales_cols =[
    col for col in sales.columns
    if col.startswith("d_")
]
print("Number of sales columns:",len(sales_cols))
print(sales_cols[:10])

Number of sales columns: 1913
['d_1', 'd_2', 'd_3', 'd_4', 'd_5', 'd_6', 'd_7', 'd_8', 'd_9', 'd_10']

The MemoryError we are seeing is happening because pandas is trying to repeat standard Python string objects (like item_id and store_id) 58,327,370 times, which consumes massive amounts of RAM.

To fix this, we must downcast your data types before you run the .melt() function. By converting your string columns to pandas category types and your numerical columns to smaller integers, you will compress the data enough to fit into memory.

Pandas is crashing because even though we optimized the data types, the .melt() function internally creates the new d column (containing the strings "d_1", "d_2", etc.) as standard Python string objects before you have a chance to convert it to a category. Trying to allocate 58.3 million Python strings in a single split-second operation overwhelms your RAM.

To bypass this internal pandas limitation, you must process the data in chunks. Because the M5 dataset is naturally divided into 10 distinct stores (e.g., CA_1, TX_2), you can loop through one store at a time, melt it, downcast it instantly, and combine them at the end.

In [5]:
import psutil

print("Sales shape:", sales.shape)

print("\nSales memory:")
sales.info(memory_usage="deep")

print("\nRAM:")
ram = psutil.virtual_memory()
print(f"Used: {ram.used / 1024**3:.2f} GB")
print(f"Available: {ram.available / 1024**3:.2f} GB")

Sales shape: (30490, 1919)

Sales memory:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30490 entries, 0 to 30489
Columns: 1919 entries, id to d_1913
dtypes: int64(1913), object(6)
memory usage: 455.4 MB

RAM:
Used: 4.59 GB
Available: 1.23 GB

In [7]:
import numpy as np
import gc

# Identify daily sales columns
sales_cols = [col for col in sales.columns if col.startswith("d_")]

print("Before:")
print(sales[sales_cols].memory_usage(deep=True).sum() / 1024**2, "MB")

# Downcast sales columns
sales[sales_cols] = sales[sales_cols].astype(np.int16)

gc.collect()

print("\nAfter:")
print(sales[sales_cols].memory_usage(deep=True).sum() / 1024**2, "MB")

print("\nDtypes:")
print(sales[sales_cols].dtypes.value_counts())

Before:
445.0026435852051 MB

After:
111.2507553100586 MB

Dtypes:
int16    1913
Name: count, dtype: int64

In [8]:
import gc

cat_cols = [
    "item_id",
    "dept_id",
    "cat_id",
    "store_id",
    "state_id"
]

for col in cat_cols:
    sales[col] = sales[col].astype("category")

gc.collect()

print("Sales memory:",
      sales.memory_usage(deep=True).sum() / 1024**2,
      "MB")

print("\nDtypes:")
print(sales.dtypes.head(10))

Sales memory: 113.9303674697876 MB

Dtypes:
id            object
item_id     category
dept_id     category
cat_id      category
store_id    category
state_id    category
d_1            int16
d_2            int16
d_3            int16
d_4            int16
dtype: object

In [10]:
print(
    sales.memory_usage(deep=True)
    .sort_values(ascending=False)
    .head(15)
)

id         2370420
item_id     315326
d_1269       60980
d_1282       60980
d_1281       60980
d_1280       60980
d_1279       60980
d_1278       60980
d_1277       60980
d_1276       60980
d_1275       60980
d_1274       60980
d_1273       60980
d_1272       60980
d_1271       60980
dtype: int64

In [11]:
print(sales[["id", "item_id", "dept_id", "cat_id", "store_id", "state_id"]].memory_usage(deep=True))

Index           132
id          2370420
item_id      315326
dept_id       31194
cat_id        30766
store_id      31320
state_id      30751
dtype: int64

In [12]:
store_groups = sales.groupby("store_id", observed=True).indices

print(store_groups.keys())

for store, indices in store_groups.items():
    print(store, len(indices))

dict_keys(['CA_1', 'CA_2', 'CA_3', 'CA_4', 'TX_1', 'TX_2', 'TX_3', 'WI_1', 'WI_2', 'WI_3'])
CA_1 3049
CA_2 3049
CA_3 3049
CA_4 3049
TX_1 3049
TX_2 3049
TX_3 3049
WI_1 3049
WI_2 3049
WI_3 3049

In [13]:
import os
import gc
import pandas as pd

output_folder = "../data/processed/melted_stores"
os.makedirs(output_folder, exist_ok=True)
# 200 days per chunk
day_chunk_size = 200
# Make sure sales_cols exists
sales_cols = [col for col in sales.columns if col.startswith("d_")]
# Process each store
for store, indices in store_groups.items():

    print(f"\nProcessing store: {store}")

    # Get only row positions for this store
    store_data = sales.iloc[indices]

    store_file = os.path.join(
        output_folder,
        f"{store}.parquet"
    )

    first_chunk = True

    # Process days in chunks
    for start in range(0, len(sales_cols), day_chunk_size):

        end = min(
            start + day_chunk_size,
            len(sales_cols)
        )

        current_days = sales_cols[start:end]

        print(
            f"  Days {start + 1} - {end} "
            f"({len(current_days)} days)"
        )

        # Select only required columns for this chunk
        chunk = store_data[
            id_cols + current_days
        ]

        # Melt
        chunk_long = chunk.melt(
            id_vars=id_cols,
            value_vars=current_days,
            var_name="d",
            value_name="sales"
        )

        # Convert d_1 → 1
        chunk_long["d"] = (
            chunk_long["d"]
            .str.replace("d_", "", regex=False)
            .astype("int16")
        )

        # Save chunk
        #
        # For now we save temporary parquet files.
        # We will combine/process them later without loading
        # everything into RAM.
        chunk_file = os.path.join(
            output_folder,
            f"{store}_{start:04d}.parquet"
        )

        chunk_long.to_parquet(
            chunk_file,
            index=False
        )

        # Release memory
        del chunk
        del chunk_long
        gc.collect()

    del store_data
    gc.collect()

    print(f"Finished {store}")

print("\nALL STORES PROCESSED")

Processing store: CA_1
  Days 1 - 200 (200 days)
  Days 201 - 400 (200 days)
  Days 401 - 600 (200 days)
  Days 601 - 800 (200 days)
  Days 801 - 1000 (200 days)
  Days 1001 - 1200 (200 days)
  Days 1201 - 1400 (200 days)
  Days 1401 - 1600 (200 days)
  Days 1601 - 1800 (200 days)
  Days 1801 - 1913 (113 days)
Finished CA_1

Processing store: CA_2
  Days 1 - 200 (200 days)
  Days 201 - 400 (200 days)
  Days 401 - 600 (200 days)
  Days 601 - 800 (200 days)
  Days 801 - 1000 (200 days)
  Days 1001 - 1200 (200 days)
  Days 1201 - 1400 (200 days)
  Days 1401 - 1600 (200 days)
  Days 1601 - 1800 (200 days)
  Days 1801 - 1913 (113 days)
Finished CA_2

Processing store: CA_3
  Days 1 - 200 (200 days)
  Days 201 - 400 (200 days)
  Days 401 - 600 (200 days)
  Days 601 - 800 (200 days)
  Days 801 - 1000 (200 days)
  Days 1001 - 1200 (200 days)
  Days 1201 - 1400 (200 days)
  Days 1401 - 1600 (200 days)
  Days 1601 - 1800 (200 days)
  Days 1801 - 1913 (113 days)
Finished CA_3

Processing store: CA_4
  Days 1 - 200 (200 days)
  Days 201 - 400 (200 days)
  Days 401 - 600 (200 days)
  Days 601 - 800 (200 days)
  Days 801 - 1000 (200 days)
  Days 1001 - 1200 (200 days)
  Days 1201 - 1400 (200 days)
  Days 1401 - 1600 (200 days)
  Days 1601 - 1800 (200 days)
  Days 1801 - 1913 (113 days)
Finished CA_4

Processing store: TX_1
  Days 1 - 200 (200 days)
  Days 201 - 400 (200 days)
  Days 401 - 600 (200 days)
  Days 601 - 800 (200 days)
  Days 801 - 1000 (200 days)
  Days 1001 - 1200 (200 days)
  Days 1201 - 1400 (200 days)
  Days 1401 - 1600 (200 days)
  Days 1601 - 1800 (200 days)
  Days 1801 - 1913 (113 days)
Finished TX_1

Processing store: TX_2
  Days 1 - 200 (200 days)
  Days 201 - 400 (200 days)
  Days 401 - 600 (200 days)
  Days 601 - 800 (200 days)
  Days 801 - 1000 (200 days)
  Days 1001 - 1200 (200 days)
  Days 1201 - 1400 (200 days)
  Days 1401 - 1600 (200 days)
  Days 1601 - 1800 (200 days)
  Days 1801 - 1913 (113 days)
Finished TX_2

Processing store: TX_3
  Days 1 - 200 (200 days)
  Days 201 - 400 (200 days)
  Days 401 - 600 (200 days)
  Days 601 - 800 (200 days)
  Days 801 - 1000 (200 days)
  Days 1001 - 1200 (200 days)
  Days 1201 - 1400 (200 days)
  Days 1401 - 1600 (200 days)
  Days 1601 - 1800 (200 days)
  Days 1801 - 1913 (113 days)
Finished TX_3

Processing store: WI_1
  Days 1 - 200 (200 days)
  Days 201 - 400 (200 days)
  Days 401 - 600 (200 days)
  Days 601 - 800 (200 days)
  Days 801 - 1000 (200 days)
  Days 1001 - 1200 (200 days)
  Days 1201 - 1400 (200 days)
  Days 1401 - 1600 (200 days)
  Days 1601 - 1800 (200 days)
  Days 1801 - 1913 (113 days)
Finished WI_1

Processing store: WI_2
  Days 1 - 200 (200 days)
  Days 201 - 400 (200 days)
  Days 401 - 600 (200 days)
  Days 601 - 800 (200 days)
  Days 801 - 1000 (200 days)
  Days 1001 - 1200 (200 days)
  Days 1201 - 1400 (200 days)
  Days 1401 - 1600 (200 days)
  Days 1601 - 1800 (200 days)
  Days 1801 - 1913 (113 days)
Finished WI_2

Processing store: WI_3
  Days 1 - 200 (200 days)
  Days 201 - 400 (200 days)
  Days 401 - 600 (200 days)
  Days 601 - 800 (200 days)
  Days 801 - 1000 (200 days)
  Days 1001 - 1200 (200 days)
  Days 1201 - 1400 (200 days)
  Days 1401 - 1600 (200 days)
  Days 1601 - 1800 (200 days)
  Days 1801 - 1913 (113 days)
Finished WI_3

ALL STORES PROCESSED

In [15]:
folder = "../data/processed/melted_stores"
test_file = os.path.join(
    folder,
    "CA_1_0000.parquet"
)

test_df = pd.read_parquet(test_file)

print("Shape:", test_df.shape)
print("\nColumns:")
print(test_df.columns.tolist())

print("\nHead:")
print(test_df.head())

print("\nMemory:")
test_df.info(memory_usage="deep")

Shape: (609800, 8)

Columns:
['id', 'item_id', 'dept_id', 'cat_id', 'store_id', 'state_id', 'd', 'sales']

Head:
                              id        item_id    dept_id   cat_id store_id  \
0  HOBBIES_1_001_CA_1_validation  HOBBIES_1_001  HOBBIES_1  HOBBIES     CA_1
1  HOBBIES_1_002_CA_1_validation  HOBBIES_1_002  HOBBIES_1  HOBBIES     CA_1
2  HOBBIES_1_003_CA_1_validation  HOBBIES_1_003  HOBBIES_1  HOBBIES     CA_1
3  HOBBIES_1_004_CA_1_validation  HOBBIES_1_004  HOBBIES_1  HOBBIES     CA_1
4  HOBBIES_1_005_CA_1_validation  HOBBIES_1_005  HOBBIES_1  HOBBIES     CA_1

  state_id  d  sales
0       CA  1      0
1       CA  1      0
2       CA  1      0
3       CA  1      0
4       CA  1      0

Memory:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 609800 entries, 0 to 609799
Data columns (total 8 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   id        609800 non-null  object
 1   item_id   609800 non-null  category
 2   dept_id   609800 non-null  category
 3   cat_id    609800 non-null  category
 4   store_id  609800 non-null  category
 5   state_id  609800 non-null  category
 6   d         609800 non-null  int16
 7   sales     609800 non-null  int16
dtypes: category(5), int16(2), object(1)
memory usage: 51.3 MB

In [20]:
import pandas as pd
import numpy as np
import gc

# -----------------------------
# Prepare CALENDAR
# -----------------------------

# Check current type first
print("Calendar d dtype:", calendar["d"].dtype)

# Convert directly to int16
calendar["d"] = calendar["d"].astype("int16")

calendar["wm_yr_wk"] = calendar["wm_yr_wk"].astype("int16")


# -----------------------------
# Prepare PRICES
# -----------------------------

prices["wm_yr_wk"] = prices["wm_yr_wk"].astype("int16")

prices["sell_price"] = prices["sell_price"].astype("float32")

prices["store_id"] = prices["store_id"].astype("category")

prices["item_id"] = prices["item_id"].astype("category")

gc.collect()


print("\nCalendar dtypes:")
print(calendar.dtypes)

print("\nPrices dtypes:")
print(prices.dtypes)

Calendar d dtype: int16

Calendar dtypes:
date            object
wm_yr_wk         int16
weekday         object
wday             int64
month            int64
year             int64
d                int16
event_name_1    object
event_type_1    object
event_name_2    object
event_type_2    object
snap_CA          int64
snap_TX          int64
snap_WI          int64
dtype: object

Prices dtypes:
store_id      category
item_id       category
wm_yr_wk         int16
sell_price     float32
dtype: object

In [21]:
print("\nCalendar d:")
print(calendar["d"].head())
print("Min:", calendar["d"].min())
print("Max:", calendar["d"].max())
print("Duplicates:", calendar["d"].duplicated().sum())

Calendar d:
0    1
1    2
2    3
3    4
4    5
Name: d, dtype: int16
Min: 1
Max: 1969
Duplicates: 0

In [ ]:
# now we use the calendar dataframe
#first we will inspect thsi
calendar.info()

To guarantee we don't hit a memory error during this specific join, just make sure those three SNAP columns are downcasted to int8 (since they only contain 0s and 1s) before you run the merge:

In [23]:

#test
folder = "../data/processed/melted_stores"
test_path = f"{folder}/CA_1_0000.parquet"
sales_long = pd.read_parquet(test_path)

print("Before merge:")
print(sales_long.shape)
print(sales_long.head())

Before merge:
(609800, 8)
                              id        item_id    dept_id   cat_id store_id  \
0  HOBBIES_1_001_CA_1_validation  HOBBIES_1_001  HOBBIES_1  HOBBIES     CA_1
1  HOBBIES_1_002_CA_1_validation  HOBBIES_1_002  HOBBIES_1  HOBBIES     CA_1
2  HOBBIES_1_003_CA_1_validation  HOBBIES_1_003  HOBBIES_1  HOBBIES     CA_1
3  HOBBIES_1_004_CA_1_validation  HOBBIES_1_004  HOBBIES_1  HOBBIES     CA_1
4  HOBBIES_1_005_CA_1_validation  HOBBIES_1_005  HOBBIES_1  HOBBIES     CA_1

  state_id  d  sales
0       CA  1      0
1       CA  1      0
2       CA  1      0
3       CA  1      0
4       CA  1      0

In [24]:
sales_long = sales_long.merge(
    calendar,
    on="d",
    how="left",
    validate="many_to_one"
)

print("After calendar merge:", sales_long.shape)

After calendar merge: (609800, 21)

In [25]:
sales_long = sales_long.merge(
    prices[
        ["store_id", "item_id", "wm_yr_wk", "sell_price"]
    ],
    on=["store_id", "item_id", "wm_yr_wk"],
    how="left",
    validate="many_to_one"
)

print("After price merge:", sales_long.shape)

print(
    "Missing price:",
    sales_long["sell_price"].isna().mean() * 100,
    "%"
)

After price merge: (609800, 22)
Missing price: 49.53492948507707 %

Read one Parquet chunk.
Merge calendar.
Merge prices.
Add the required features.
Save the processed chunk as another Parquet file.
Delete it from RAM.
Move to the next chunk.

In [35]:
import os
import gc
import pandas as pd

input_folder = "../data/processed/melted_stores"
output_folder = "../data/processed/merged_chunks"

os.makedirs(output_folder, exist_ok=True)

files = [
    f for f in os.listdir(input_folder)
    if f.endswith(".parquet")
]

files = sorted(files)

print("Total files:", len(files))
print(files[:5])
print(files[-5:])

Total files: 100
['CA_1_0000.parquet', 'CA_1_0200.parquet', 'CA_1_0400.parquet', 'CA_1_0600.parquet', 'CA_1_0800.parquet']
['WI_3_1000.parquet', 'WI_3_1200.parquet', 'WI_3_1400.parquet', 'WI_3_1600.parquet', 'WI_3_1800.parquet']

In [36]:
import os
import gc
import pandas as pd

input_folder = "../data/processed/melted_stores"
output_folder = "../data/processed/merged_chunks"

os.makedirs(output_folder, exist_ok=True)

files = sorted([
    f for f in os.listdir(input_folder)
    if f.endswith(".parquet")
])
for i, file in enumerate(files, 1):
    input_path = os.path.join(input_folder, file)
    output_path = os.path.join(output_folder, file)

    print(f"\n[{i}/100] Processing: {file}")

    # Skip if already processed
    if os.path.exists(output_path):
        print("Already processed — skipping.")
        continue
    # Read one chunk
    sales_long = pd.read_parquet(input_path)

    print("  Initial shape:", sales_long.shape)
    # Calendar merge
    sales_long = sales_long.merge(
        calendar,
        on="d",
        how="left",
        validate="many_to_one"
    )
    # Price merge
    sales_long = sales_long.merge(
        prices[["store_id", "item_id", "wm_yr_wk", "sell_price"]],
        on=["store_id", "item_id", "wm_yr_wk"],
        how="left",
        validate="many_to_one"
    )

    print("  After merge:", sales_long.shape)

    # Save
    sales_long.to_parquet(
        output_path,
        index=False
    )

    print("  Saved:", output_path)

    # Free RAM
    del sales_long
    gc.collect()

print("\n========== ALL 100 FILES PROCESSED ==========")

[1/100] Processing: CA_1_0000.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\CA_1_0000.parquet

[2/100] Processing: CA_1_0200.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\CA_1_0200.parquet

[3/100] Processing: CA_1_0400.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\CA_1_0400.parquet

[4/100] Processing: CA_1_0600.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\CA_1_0600.parquet

[5/100] Processing: CA_1_0800.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\CA_1_0800.parquet

[6/100] Processing: CA_1_1000.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\CA_1_1000.parquet

[7/100] Processing: CA_1_1200.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\CA_1_1200.parquet

[8/100] Processing: CA_1_1400.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\CA_1_1400.parquet

[9/100] Processing: CA_1_1600.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\CA_1_1600.parquet

[10/100] Processing: CA_1_1800.parquet
  Initial shape: (344537, 8)
  After merge: (344537, 22)
  Saved: ../data/processed/merged_chunks\CA_1_1800.parquet

[11/100] Processing: CA_2_0000.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\CA_2_0000.parquet

[12/100] Processing: CA_2_0200.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\CA_2_0200.parquet

[13/100] Processing: CA_2_0400.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\CA_2_0400.parquet

[14/100] Processing: CA_2_0600.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\CA_2_0600.parquet

[15/100] Processing: CA_2_0800.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\CA_2_0800.parquet

[16/100] Processing: CA_2_1000.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\CA_2_1000.parquet

[17/100] Processing: CA_2_1200.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\CA_2_1200.parquet

[18/100] Processing: CA_2_1400.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\CA_2_1400.parquet

[19/100] Processing: CA_2_1600.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\CA_2_1600.parquet

[20/100] Processing: CA_2_1800.parquet
  Initial shape: (344537, 8)
  After merge: (344537, 22)
  Saved: ../data/processed/merged_chunks\CA_2_1800.parquet

[21/100] Processing: CA_3_0000.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\CA_3_0000.parquet

[22/100] Processing: CA_3_0200.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\CA_3_0200.parquet

[23/100] Processing: CA_3_0400.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\CA_3_0400.parquet

[24/100] Processing: CA_3_0600.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\CA_3_0600.parquet

[25/100] Processing: CA_3_0800.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\CA_3_0800.parquet

[26/100] Processing: CA_3_1000.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\CA_3_1000.parquet

[27/100] Processing: CA_3_1200.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\CA_3_1200.parquet

[28/100] Processing: CA_3_1400.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\CA_3_1400.parquet

[29/100] Processing: CA_3_1600.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\CA_3_1600.parquet

[30/100] Processing: CA_3_1800.parquet
  Initial shape: (344537, 8)
  After merge: (344537, 22)
  Saved: ../data/processed/merged_chunks\CA_3_1800.parquet

[31/100] Processing: CA_4_0000.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\CA_4_0000.parquet

[32/100] Processing: CA_4_0200.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\CA_4_0200.parquet

[33/100] Processing: CA_4_0400.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\CA_4_0400.parquet

[34/100] Processing: CA_4_0600.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\CA_4_0600.parquet

[35/100] Processing: CA_4_0800.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\CA_4_0800.parquet

[36/100] Processing: CA_4_1000.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\CA_4_1000.parquet

[37/100] Processing: CA_4_1200.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\CA_4_1200.parquet

[38/100] Processing: CA_4_1400.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\CA_4_1400.parquet

[39/100] Processing: CA_4_1600.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\CA_4_1600.parquet

[40/100] Processing: CA_4_1800.parquet
  Initial shape: (344537, 8)
  After merge: (344537, 22)
  Saved: ../data/processed/merged_chunks\CA_4_1800.parquet

[41/100] Processing: TX_1_0000.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\TX_1_0000.parquet

[42/100] Processing: TX_1_0200.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\TX_1_0200.parquet

[43/100] Processing: TX_1_0400.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\TX_1_0400.parquet

[44/100] Processing: TX_1_0600.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\TX_1_0600.parquet

[45/100] Processing: TX_1_0800.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\TX_1_0800.parquet

[46/100] Processing: TX_1_1000.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\TX_1_1000.parquet

[47/100] Processing: TX_1_1200.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\TX_1_1200.parquet

[48/100] Processing: TX_1_1400.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\TX_1_1400.parquet

[49/100] Processing: TX_1_1600.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\TX_1_1600.parquet

[50/100] Processing: TX_1_1800.parquet
  Initial shape: (344537, 8)
  After merge: (344537, 22)
  Saved: ../data/processed/merged_chunks\TX_1_1800.parquet

[51/100] Processing: TX_2_0000.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\TX_2_0000.parquet

[52/100] Processing: TX_2_0200.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\TX_2_0200.parquet

[53/100] Processing: TX_2_0400.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\TX_2_0400.parquet

[54/100] Processing: TX_2_0600.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\TX_2_0600.parquet

[55/100] Processing: TX_2_0800.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\TX_2_0800.parquet

[56/100] Processing: TX_2_1000.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\TX_2_1000.parquet

[57/100] Processing: TX_2_1200.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\TX_2_1200.parquet

[58/100] Processing: TX_2_1400.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\TX_2_1400.parquet

[59/100] Processing: TX_2_1600.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\TX_2_1600.parquet

[60/100] Processing: TX_2_1800.parquet
  Initial shape: (344537, 8)
  After merge: (344537, 22)
  Saved: ../data/processed/merged_chunks\TX_2_1800.parquet

[61/100] Processing: TX_3_0000.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\TX_3_0000.parquet

[62/100] Processing: TX_3_0200.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\TX_3_0200.parquet

[63/100] Processing: TX_3_0400.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\TX_3_0400.parquet

[64/100] Processing: TX_3_0600.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\TX_3_0600.parquet

[65/100] Processing: TX_3_0800.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\TX_3_0800.parquet

[66/100] Processing: TX_3_1000.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\TX_3_1000.parquet

[67/100] Processing: TX_3_1200.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\TX_3_1200.parquet

[68/100] Processing: TX_3_1400.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\TX_3_1400.parquet

[69/100] Processing: TX_3_1600.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\TX_3_1600.parquet

[70/100] Processing: TX_3_1800.parquet
  Initial shape: (344537, 8)
  After merge: (344537, 22)
  Saved: ../data/processed/merged_chunks\TX_3_1800.parquet

[71/100] Processing: WI_1_0000.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\WI_1_0000.parquet

[72/100] Processing: WI_1_0200.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\WI_1_0200.parquet

[73/100] Processing: WI_1_0400.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\WI_1_0400.parquet

[74/100] Processing: WI_1_0600.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\WI_1_0600.parquet

[75/100] Processing: WI_1_0800.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\WI_1_0800.parquet

[76/100] Processing: WI_1_1000.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\WI_1_1000.parquet

[77/100] Processing: WI_1_1200.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\WI_1_1200.parquet

[78/100] Processing: WI_1_1400.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\WI_1_1400.parquet

[79/100] Processing: WI_1_1600.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\WI_1_1600.parquet

[80/100] Processing: WI_1_1800.parquet
  Initial shape: (344537, 8)
  After merge: (344537, 22)
  Saved: ../data/processed/merged_chunks\WI_1_1800.parquet

[81/100] Processing: WI_2_0000.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\WI_2_0000.parquet

[82/100] Processing: WI_2_0200.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\WI_2_0200.parquet

[83/100] Processing: WI_2_0400.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\WI_2_0400.parquet

[84/100] Processing: WI_2_0600.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\WI_2_0600.parquet

[85/100] Processing: WI_2_0800.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\WI_2_0800.parquet

[86/100] Processing: WI_2_1000.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\WI_2_1000.parquet

[87/100] Processing: WI_2_1200.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\WI_2_1200.parquet

[88/100] Processing: WI_2_1400.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\WI_2_1400.parquet

[89/100] Processing: WI_2_1600.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\WI_2_1600.parquet

[90/100] Processing: WI_2_1800.parquet
  Initial shape: (344537, 8)
  After merge: (344537, 22)
  Saved: ../data/processed/merged_chunks\WI_2_1800.parquet

[91/100] Processing: WI_3_0000.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\WI_3_0000.parquet

[92/100] Processing: WI_3_0200.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\WI_3_0200.parquet

[93/100] Processing: WI_3_0400.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\WI_3_0400.parquet

[94/100] Processing: WI_3_0600.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\WI_3_0600.parquet

[95/100] Processing: WI_3_0800.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\WI_3_0800.parquet

[96/100] Processing: WI_3_1000.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\WI_3_1000.parquet

[97/100] Processing: WI_3_1200.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\WI_3_1200.parquet

[98/100] Processing: WI_3_1400.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\WI_3_1400.parquet

[99/100] Processing: WI_3_1600.parquet
  Initial shape: (609800, 8)
  After merge: (609800, 22)
  Saved: ../data/processed/merged_chunks\WI_3_1600.parquet

[100/100] Processing: WI_3_1800.parquet
  Initial shape: (344537, 8)
  After merge: (344537, 22)
  Saved: ../data/processed/merged_chunks\WI_3_1800.parquet

========== ALL 100 FILES PROCESSED ==========

In [38]:
import pandas as pd

file_path = "../data/processed/merged_chunks/CA_1_0000.parquet"

sales_long = pd.read_parquet(file_path)

print("Shape:", sales_long.shape)

print("\nColumns:")
print(sales_long.columns.tolist())

print("\nDtypes:")
print(sales_long.dtypes)

print("\nFirst 10 rows:")
display(sales_long.head(10))

print("\nLast 10 rows:")
display(sales_long.tail(10))

print("\nDay range:")
print(sales_long["d"].min(), "to", sales_long["d"].max())

print("\nUnique items:", sales_long["item_id"].nunique())
print("Unique stores:", sales_long["store_id"].nunique())

Shape: (609800, 22)

Columns:
['id', 'item_id', 'dept_id', 'cat_id', 'store_id', 'state_id', 'd', 'sales', 'date', 'wm_yr_wk', 'weekday', 'wday', 'month', 'year', 'event_name_1', 'event_type_1', 'event_name_2', 'event_type_2', 'snap_CA', 'snap_TX', 'snap_WI', 'sell_price']

Dtypes:
id                object
item_id         category
dept_id         category
cat_id          category
store_id        category
state_id        category
d                  int16
sales              int16
date              object
wm_yr_wk           int16
weekday           object
wday               int64
month              int64
year               int64
event_name_1      object
event_type_1      object
event_name_2      object
event_type_2      object
snap_CA            int64
snap_TX            int64
snap_WI            int64
sell_price       float32
dtype: object

First 10 rows:

,id,item_id,dept_id,cat_id,store_id,state_id,d,sales,date,wm_yr_wk,...,month,year,event_name_1,event_type_1,event_name_2,event_type_2,snap_CA,snap_TX,snap_WI,sell_price
0,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,1,0,2011-01-29,11101,...,1,2011,None,None,None,None,0,0,0,NaN
1,HOBBIES_1_002_CA_1_validation,HOBBIES_1_002,HOBBIES_1,HOBBIES,CA_1,CA,1,0,2011-01-29,11101,...,1,2011,None,None,None,None,0,0,0,NaN
2,HOBBIES_1_003_CA_1_validation,HOBBIES_1_003,HOBBIES_1,HOBBIES,CA_1,CA,1,0,2011-01-29,11101,...,1,2011,None,None,None,None,0,0,0,NaN
3,HOBBIES_1_004_CA_1_validation,HOBBIES_1_004,HOBBIES_1,HOBBIES,CA_1,CA,1,0,2011-01-29,11101,...,1,2011,None,None,None,None,0,0,0,NaN
4,HOBBIES_1_005_CA_1_validation,HOBBIES_1_005,HOBBIES_1,HOBBIES,CA_1,CA,1,0,2011-01-29,11101,...,1,2011,None,None,None,None,0,0,0,NaN
5,HOBBIES_1_006_CA_1_validation,HOBBIES_1_006,HOBBIES_1,HOBBIES,CA_1,CA,1,0,2011-01-29,11101,...,1,2011,None,None,None,None,0,0,0,NaN
6,HOBBIES_1_007_CA_1_validation,HOBBIES_1_007,HOBBIES_1,HOBBIES,CA_1,CA,1,0,2011-01-29,11101,...,1,2011,None,None,None,None,0,0,0,NaN
7,HOBBIES_1_008_CA_1_validation,HOBBIES_1_008,HOBBIES_1,HOBBIES,CA_1,CA,1,12,2011-01-29,11101,...,1,2011,None,None,None,None,0,0,0,0.46
8,HOBBIES_1_009_CA_1_validation,HOBBIES_1_009,HOBBIES_1,HOBBIES,CA_1,CA,1,2,2011-01-29,11101,...,1,2011,None,None,None,None,0,0,0,1.56
9,HOBBIES_1_010_CA_1_validation,HOBBIES_1_010,HOBBIES_1,HOBBIES,CA_1,CA,1,0,2011-01-29,11101,...,1,2011,None,None,None,None,0,0,0,3.17

Last 10 rows:

,id,item_id,dept_id,cat_id,store_id,state_id,d,sales,date,wm_yr_wk,...,month,year,event_name_1,event_type_1,event_name_2,event_type_2,snap_CA,snap_TX,snap_WI,sell_price
609790,FOODS_3_818_CA_1_validation,FOODS_3_818,FOODS_3,FOODS,CA_1,CA,200,0,2011-08-16,11129,...,8,2011,None,None,None,None,0,0,0,NaN
609791,FOODS_3_819_CA_1_validation,FOODS_3_819,FOODS_3,FOODS,CA_1,CA,200,3,2011-08-16,11129,...,8,2011,None,None,None,None,0,0,0,1.98
609792,FOODS_3_820_CA_1_validation,FOODS_3_820,FOODS_3,FOODS,CA_1,CA,200,1,2011-08-16,11129,...,8,2011,None,None,None,None,0,0,0,1.98
609793,FOODS_3_821_CA_1_validation,FOODS_3_821,FOODS_3,FOODS,CA_1,CA,200,0,2011-08-16,11129,...,8,2011,None,None,None,None,0,0,0,NaN
609794,FOODS_3_822_CA_1_validation,FOODS_3_822,FOODS_3,FOODS,CA_1,CA,200,3,2011-08-16,11129,...,8,2011,None,None,None,None,0,0,0,4.28
609795,FOODS_3_823_CA_1_validation,FOODS_3_823,FOODS_3,FOODS,CA_1,CA,200,0,2011-08-16,11129,...,8,2011,None,None,None,None,0,0,0,NaN
609796,FOODS_3_824_CA_1_validation,FOODS_3_824,FOODS_3,FOODS,CA_1,CA,200,2,2011-08-16,11129,...,8,2011,None,None,None,None,0,0,0,2.48
609797,FOODS_3_825_CA_1_validation,FOODS_3_825,FOODS_3,FOODS,CA_1,CA,200,0,2011-08-16,11129,...,8,2011,None,None,None,None,0,0,0,3.98
609798,FOODS_3_826_CA_1_validation,FOODS_3_826,FOODS_3,FOODS,CA_1,CA,200,0,2011-08-16,11129,...,8,2011,None,None,None,None,0,0,0,NaN
609799,FOODS_3_827_CA_1_validation,FOODS_3_827,FOODS_3,FOODS,CA_1,CA,200,0,2011-08-16,11129,...,8,2011,None,None,None,None,0,0,0,NaN

Day range:
1 to 200

Unique items: 3049
Unique stores: 1

In [37]:
import os
merged_folder = "../data/processed/merged_chunks"
merged_files = sorted([
    f for f in os.listdir(merged_folder)
    if f.endswith(".parquet")
])

print("Total merged files:", len(merged_files))
print(merged_files[:3])
print(merged_files[-3:])

Total merged files: 100
['CA_1_0000.parquet', 'CA_1_0200.parquet', 'CA_1_0400.parquet']
['WI_3_1400.parquet', 'WI_3_1600.parquet', 'WI_3_1800.parquet']

In [ ]:
sales_long.info()

Now before moving forward we should verify that we merged our dataset correctly and the following points
wide -> long
d_1,d_2 are preserved
calendar dataframe successfully mapped 
Actual dates available  chunks: 344,537 row
No unexpected missing values

In [39]:
print(sales_long.shape)
print(sales_long[["item_id", "store_id", "d", "date","wm_yr_wk", "sales"]].head(10))
print(sales_long["date"].min())#minimum date or starting date 
print(sales_long["date"].max())
print(sales_long["sales"].isna().sum())
print(sales_long["date"].isna().sum())

(609800, 22)
         item_id store_id  d        date  wm_yr_wk  sales
0  HOBBIES_1_001     CA_1  1  2011-01-29     11101      0
1  HOBBIES_1_002     CA_1  1  2011-01-29     11101      0
2  HOBBIES_1_003     CA_1  1  2011-01-29     11101      0
3  HOBBIES_1_004     CA_1  1  2011-01-29     11101      0
4  HOBBIES_1_005     CA_1  1  2011-01-29     11101      0
5  HOBBIES_1_006     CA_1  1  2011-01-29     11101      0
6  HOBBIES_1_007     CA_1  1  2011-01-29     11101      0
7  HOBBIES_1_008     CA_1  1  2011-01-29     11101     12
8  HOBBIES_1_009     CA_1  1  2011-01-29     11101      2
9  HOBBIES_1_010     CA_1  1  2011-01-29     11101      0
2011-01-29
2011-08-16
0
0

In [ ]:
# d_1 ->2011-01--29 lets check another day
sales_long[sales_long["d"]==2][["item_id", "store_id", "d", "date","wm_yr_wk", "sales"]
].head()

In [ ]:
sales_long[
    [
        "date",
        "weekday",
        "event_name_1",
        "event_type_1",
        "snap_CA",
        "snap_TX",
        "snap_WI"
    ]
].head(10)

In [ ]:
#lets inspect the price data
prices.head()

In [ ]:
prices.shape

Before merging — very important check

We don't want a merge to unexpectedly multiply our rows.
sales_long
1,913,000 rows
If we merge incorrectly and suddenly get:
2,500,000 rows

that's a warning.

Why?

Because we may have created a many-to-many merge.

For our desired relationship:

sales observation
        ↓
one matching price

we expect each sales row to find at most one relevant price.

This is another important concept:

A correct join should preserve the intended grain of the dataset.

our grain item + store + date

In [ ]:
price_key = [
    "store_id",
    "item_id",
    "wm_yr_wk"
]
#lets check do we have a composite key (duplicate) before merging the dataset
prices.duplicated(
    subset=price_key
).sum()

In [ ]:
prices.groupby(price_key).size().value_counts().sort_index()

In [ ]:
prices[["store_id", "item_id", "wm_yr_wk", "sell_price"]].head(10)

In [ ]:
prices[
    (prices["item_id"] == "HOBBIES_1_001") &
    (prices["store_id"] == "CA_1") &
    (prices["wm_yr_wk"] == 11325)
]

# before merging it we need to optimize the prices dataframe 
If store_id and item_id in your prices table are still standard strings (object), merging them with sales_long (where we already converted them to category) will force pandas to convert everything back into standard strings during the join. This will immediately trigger another MemoryError.

To ensure the join is fast and memory-safe, the data types of the join keys must match perfectly, and the new sell_price column should be shrunk to a float32.

import gc

# 1. Delete the original wide dataframe from RAM (we only need sales_long now)
try:
    del sales
except NameError:
    pass

# Force Python to instantly release the freed memory back to your computer
gc.collect()

# 2. Force 'prices' to use the EXACT same categorical dictionary as 'sales_long'
prices['store_id'] = prices['store_id'].astype(sales_long['store_id'].dtype)
prices['item_id'] = prices['item_id'].astype(sales_long['item_id'].dtype)

# (Ensure these are still downcasted from our previous step)
prices['wm_yr_wk'] = prices['wm_yr_wk'].astype('int16')
prices['sell_price'] = prices['sell_price'].astype('float32')

# 3. Now execute the merge with plenty of free RAM
print("Starting memory-safe price merge...")
sales_long = sales_long.merge(
    prices,
    on=["store_id", "item_id", "wm_yr_wk"],
    how="left"
)

# 4. Clean up the 'prices' dataframe to free even more RAM
del prices
gc.collect()

print("Merge successful! Shape:", sales_long.shape)'

The issue here is not your data types anymore. It is a known limitation in how pandas performs joins. When you merge on multiple columns (store_id, item_id, wm_yr_wk), pandas tries to create a massive temporary "hash index" mapping all 58.3 million combinations. That specific temporary index requires exactly 445 MB of contiguous RAM, and your system physically cannot provide it.

We will use the exact same strategy we used to fix the .melt() error earlier: Chunking by Store.

By isolating one store at a time, we reduce the merge operation from 58 million rows down to just 5.8 million rows. Even better, because we are processing one store at a time, we don't even need to use store_id as a merge key anymore, which skips that massive hash index completely.

In [ ]:
import gc
import pandas as pd

print("Starting chunked price merge...")

# Get the list of unique stores
stores = sales_long['store_id'].unique()
merged_chunks = []

for store in stores:
    print(f"Processing prices for store: {store}...")
    
    # 1. Isolate the sales and prices for JUST this one store
    sales_chunk = sales_long[sales_long['store_id'] == store]
    price_chunk = prices[prices['store_id'] == store]
    
    # 2. Merge the chunk
    # Notice we drop 'store_id' from the 'on' list because we already filtered for it!
    # This prevents pandas from building the 445MB hash array.
    merged_chunk = sales_chunk.merge(
        price_chunk[['item_id', 'wm_yr_wk', 'sell_price']], 
        on=['item_id', 'wm_yr_wk'], 
        how='left'
    )
    
    # 3. Save the completed chunk
    merged_chunks.append(merged_chunk)
    
    # 4. Nuke the temporary variables from RAM instantly
    del sales_chunk, price_chunk, merged_chunk
    gc.collect()

print("Recombining all stores...")
# 5. Overwrite the old sales_long with the new combined one
sales_long = pd.concat(merged_chunks, ignore_index=True)

# 6. Delete the original prices table and chunks list to free up maximum RAM
del prices, merged_chunks
gc.collect()

print("Merge fully complete! Shape:", sales_long.shape)

test_merge = sales_long.merge(
    prices,
    on=["store_id", "item_id", "wm_yr_wk"],
    how="left"
)
test_merge

In [ ]:
print("Before merge:", sales_long.shape)
print("After merge:", test_merge.shape)

In [ ]:
print("Missing prices:", test_merge["sell_price"].isna().sum())

print(
    "Missing price percentage:",
    test_merge["sell_price"].isna().mean() * 100
)

In [ ]:
# Note that this missing value and other applied on 
# our sample not on entire M5 dataset
#before filling missing values lets analyze our merged dataset

In [ ]:
#Check whether missing prices are concentrated at the beginning
missing_price = test_merge[
    test_merge["sell_price"].isna()
]

missing_price[
    ["item_id", "store_id", "date", "wm_yr_wk", "sales"]
].head(20)

In [ ]:
missing_price["date"].min(), missing_price["date"].max()

In [ ]:
test_merge.groupby(
    test_merge["sell_price"].isna()
)["date"].agg(["min", "max", "count"])

In [ ]:
#Check whether missing price rows actually have sales
missing_price.groupby(
    "sales"
).size().sort_index().head(20)

In [ ]:
missing_price['sales'].sum()

In [ ]:
#Check one specific product
sample_item = missing_price.iloc[0]["item_id"]
sample_store = missing_price.iloc[0]["store_id"]

test_merge[
    (test_merge["item_id"] == sample_item) &
    (test_merge["store_id"] == sample_store)
][
    ["item_id", "store_id", "date", "wm_yr_wk", "sales", "sell_price"]
].tail(30)

But let's verify one more thing before deciding how to handle them.

We need to know whether the missing-price rows always have zero sales, not just the total being zero. The sum being 0 strongly suggests that, because sales can't be negative, but let's explicitly verify it.

In [ ]:
missing_price["sales"].value_counts()
#So every single observation with a missing price has zero sales in our current dataset

In [ ]:
test_merge.groupby(
    test_merge["sell_price"].isna()
)["sales"].agg(
    ["count", "sum", "min", "max"]
)

# Step 1 Validate the forecasting grain
- Does every row represent exactly one product + one store + one date?

In [ ]:
#Our intended grain is:item_id + store_id + date
key_cols = ["item_id", "store_id", "date"]

duplicate_count = test_merge.duplicated(
    subset=key_cols
).sum()

duplicate_count

In [ ]:
#We've already discovered that sell_price has missing values. Now let's verify all columns at once.
missing_values = test_merge.isna().sum().sort_values(ascending=False)

missing_values#we donot need to fix sell_price right now because in our
# current sample all Nan price have sales =0 almost except some

In [ ]:
#checking the datatype
test_merge.dtypes

In [ ]:
#now lets check the distribution of sales 
test_merge['sales'].describe()

# Observation
- 1. count = 1,913,000 We have 1.913 million daily product-store observations in this sample.
- Remember 1000 original product/store rows × 1913 days = 1,913,000 observations.
- 2. Mean = 0.920 On average, each product-store-day observation has about:
- 0.92 units sold per day across different product in our sample
- Median That means at least half of the observations have sales of 0 units.
- This means 75% of observations have sales ≤ 1 unit.

- So most daily observations are very small.

- The distribution is therefore heavily concentrated near zero.
- 5. Maximum = 294

- Some product-store-day combinations sold as many as:

- 294 units in one day.

- That's a huge difference compared with the median of 0.This tells us the distribution is strongly right-skewed.

In [ ]:
#Let's verify the exact percentage of zero-sales observations rather than relying on our earlier calculation.
zero_sales_pct = (test_merge["sales"] == 0).mean() * 100

zero_sales_pct

Approximately 67.21% of the product-store-day observations in our 1000-row sales sample have zero sales.
Out of the 1,913,000 product-store-day observations in our transformed sample, about 67.21% had sales = 0.

In [ ]:
#calculate the actual count
zero_sales_count = (test_merge["sales"] == 0).sum()

zero_sales_count

In [ ]:
non_zero_sales_count = (test_merge["sales"] > 0).sum()

non_zero_sales_count

In [ ]:
#now investigating the price distribution
test_merge["sell_price"].describe()

### Price Distribution

Among observations with an available sell_price:

- Count: 1,520,496
- Mean price: 5.22
- Median price: 3.97
- Standard deviation: 4.33
- Minimum price: 0.01
- Maximum price: 30.98

The mean is higher than the median, indicating that higher-priced
observations increase the average price.

The minimum and maximum values are not automatically treated as
errors or removed as outliers. Their validity should be evaluated
using business and product context before any outlier treatment.

Check date continuity 
We want to know whether a product-store time series has continuous daily dates.
we want:

April 1
April 2
April 3
April 4
April 5
and not:

April 1
April 2
April 5
April 6

Why?
Because later we'll create features such as:

sales_lag_1
sales_lag_7
sales_lag_28

If dates are missing, a "7-day lag" could accidentally represent something other than exactly 7 calendar days.

In [ ]:
series = test_merge[
    (test_merge["item_id"] == "HOBBIES_1_001") &
    (test_merge["store_id"] == "CA_1")
].sort_values("date")
#we are checking the difference between consecutive dates
series["date"].diff().dropna().value_counts()

our selected series HOBBIES_1_001 + CA_1 contains 1,913 consecutive daily observations.There are 1,912 gaps between those 1,913 dates, and every gap is exactly 1 day.But in our sample not in 

No missing calendar dates in this particular product-store series.
Data validation is now complete

import os

os.makedirs("../data/processed", exist_ok=True)

test_merge.to_parquet(
    "../data/processed/full_analytical data.parquet",
    index=False
)

In [ ]:
pd.read_parquet(
    "../data/processed/analytical_sample.parquet"
).shape

In [ ]:
test_merge.columns.tolist()

In [ ]:
test_merge["sell_price"].isna().sum()