In this notebook we will create additional information basically we will perform feature engineering

In [53]:
import pandas as pd
import datetime as dt
df = pd.read_parquet(
    "../data/processed/analytical_sample.parquet"
)

df.head()

,id,item_id,dept_id,cat_id,store_id,state_id,d,sales,date,wm_yr_wk,sell_price
0,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,NaN
1,HOBBIES_1_002_CA_1_validation,HOBBIES_1_002,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,NaN
2,HOBBIES_1_003_CA_1_validation,HOBBIES_1_003,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,NaN
3,HOBBIES_1_004_CA_1_validation,HOBBIES_1_004,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,NaN
4,HOBBIES_1_005_CA_1_validation,HOBBIES_1_005,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,NaN

In [54]:
df.shape

(1913000, 11)

In [55]:
df["year"]=df["date"].dt.year
df

,id,item_id,dept_id,cat_id,store_id,state_id,d,sales,date,wm_yr_wk,sell_price,year
0,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,NaN,2011
1,HOBBIES_1_002_CA_1_validation,HOBBIES_1_002,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,NaN,2011
2,HOBBIES_1_003_CA_1_validation,HOBBIES_1_003,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,NaN,2011
3,HOBBIES_1_004_CA_1_validation,HOBBIES_1_004,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,NaN,2011
4,HOBBIES_1_005_CA_1_validation,HOBBIES_1_005,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,NaN,2011
...,...,...,...,...,...,...,...,...,...,...,...,...
1912995,HOUSEHOLD_1_440_CA_1_validation,HOUSEHOLD_1_440,HOUSEHOLD_1,HOUSEHOLD,CA_1,CA,d_1913,1,2016-04-24,11613,14.97,2016
1912996,HOUSEHOLD_1_441_CA_1_validation,HOUSEHOLD_1_441,HOUSEHOLD_1,HOUSEHOLD,CA_1,CA,d_1913,5,2016-04-24,11613,2.77,2016
1912997,HOUSEHOLD_1_442_CA_1_validation,HOUSEHOLD_1_442,HOUSEHOLD_1,HOUSEHOLD,CA_1,CA,d_1913,0,2016-04-24,11613,8.97,2016
1912998,HOUSEHOLD_1_443_CA_1_validation,HOUSEHOLD_1_443,HOUSEHOLD_1,HOUSEHOLD,CA_1,CA,d_1913,0,2016-04-24,11613,2.47,2016
1912999,HOUSEHOLD_1_444_CA_1_validation,HOUSEHOLD_1_444,HOUSEHOLD_1,HOUSEHOLD,CA_1,CA,d_1913,0,2016-04-24,11613,4.88,2016

In [56]:
#creating month
df["month"]=df["date"].dt.month
df["day_of_week"]=df["date"].dt.dayofweek

In [57]:
#create a feature to check whether the date is weekend date or not
df["is_weekend"] = (df["day_of_week"] >= 5).astype(int)

In [58]:
# checking the new features with dates
df[
    [
        "date",
        "year",
        "month",
        "day_of_week",
        "is_weekend"
    ]
].sample(15)

              date  year  month  day_of_week  is_weekend
1616373 2015-07-03  2015      7            4           0
1503460 2015-03-12  2015      3            3           0
691118  2012-12-20  2012     12            3           0
1197163 2014-05-10  2014      5            5           1
1370008 2014-10-30  2014     10            3           0
847835  2013-05-25  2013      5            5           1
1786413 2015-12-20  2015     12            6           1
1627877 2015-07-14  2015      7            1           0
944041  2013-08-30  2013      8            4           0
514741  2012-06-26  2012      6            1           0
1506652 2015-03-15  2015      3            6           1
94107   2011-05-03  2011      5            1           0
1605353 2015-06-22  2015      6            0           0
783547  2013-03-22  2013      3            4           0
51367   2011-03-21  2011      3            0           0

# now lets create the lag features for extracting the previous sales unit sold

Our data contains many different product-store series:

HOBBIES_1_001 + CA_1
HOBBIES_1_001 + CA_2
HOBBIES_1_002 + CA_1
...

We must not calculate one global lag.

For example, this would be wrong:

Product A, CA_1 → Apr 10 sales
Product B, CA_1 → Apr 11 sales

Product B's previous row isn't necessarily Product A's previous day.

Instead, we calculate the lag within each product-store group.


Product A + Store A

Jan 1
Jan 2
Jan 3
Jan 4 not a random order

In [59]:
# sort the data so that future sales not come before
#Because shift() works according to row order.
df = df.sort_values(
    ["item_id", "store_id", "date"]
).reset_index(drop=True)

In [60]:
df

,id,item_id,dept_id,cat_id,store_id,state_id,d,sales,date,wm_yr_wk,sell_price,year,month,day_of_week,is_weekend
0,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,NaN,2011,1,5,1
1,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_2,0,2011-01-30,11101,NaN,2011,1,6,1
2,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_3,0,2011-01-31,11101,NaN,2011,1,0,0
3,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_4,0,2011-02-01,11101,NaN,2011,2,1,0
4,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_5,0,2011-02-02,11101,NaN,2011,2,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1912995,HOUSEHOLD_1_444_CA_1_validation,HOUSEHOLD_1_444,HOUSEHOLD_1,HOUSEHOLD,CA_1,CA,d_1909,0,2016-04-20,11612,4.88,2016,4,2,0
1912996,HOUSEHOLD_1_444_CA_1_validation,HOUSEHOLD_1_444,HOUSEHOLD_1,HOUSEHOLD,CA_1,CA,d_1910,2,2016-04-21,11612,4.88,2016,4,3,0
1912997,HOUSEHOLD_1_444_CA_1_validation,HOUSEHOLD_1_444,HOUSEHOLD_1,HOUSEHOLD,CA_1,CA,d_1911,2,2016-04-22,11612,4.88,2016,4,4,0
1912998,HOUSEHOLD_1_444_CA_1_validation,HOUSEHOLD_1_444,HOUSEHOLD_1,HOUSEHOLD,CA_1,CA,d_1912,0,2016-04-23,11613,4.88,2016,4,5,1
1912999,HOUSEHOLD_1_444_CA_1_validation,HOUSEHOLD_1_444,HOUSEHOLD_1,HOUSEHOLD,CA_1,CA,d_1913,0,2016-04-24,11613,4.88,2016,4,6,1

In [61]:
df["sales_lag_1"] = (
    df
    .groupby(["item_id", "store_id"])["sales"]
    .shift(1)
)
# we are just doing  group the data and then take sales then lag or shift

Separate the data into individual product-store time series.
groupby(["item_id", "store_id"])
Take:-
df["sales"]

then .shift(1) Move the previous sales value down by one row.

In [62]:
df

,id,item_id,dept_id,cat_id,store_id,state_id,d,sales,date,wm_yr_wk,sell_price,year,month,day_of_week,is_weekend,sales_lag_1
0,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,NaN,2011,1,5,1,NaN
1,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_2,0,2011-01-30,11101,NaN,2011,1,6,1,0.0
2,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_3,0,2011-01-31,11101,NaN,2011,1,0,0,0.0
3,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_4,0,2011-02-01,11101,NaN,2011,2,1,0,0.0
4,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_5,0,2011-02-02,11101,NaN,2011,2,2,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1912995,HOUSEHOLD_1_444_CA_1_validation,HOUSEHOLD_1_444,HOUSEHOLD_1,HOUSEHOLD,CA_1,CA,d_1909,0,2016-04-20,11612,4.88,2016,4,2,0,0.0
1912996,HOUSEHOLD_1_444_CA_1_validation,HOUSEHOLD_1_444,HOUSEHOLD_1,HOUSEHOLD,CA_1,CA,d_1910,2,2016-04-21,11612,4.88,2016,4,3,0,0.0
1912997,HOUSEHOLD_1_444_CA_1_validation,HOUSEHOLD_1_444,HOUSEHOLD_1,HOUSEHOLD,CA_1,CA,d_1911,2,2016-04-22,11612,4.88,2016,4,4,0,2.0
1912998,HOUSEHOLD_1_444_CA_1_validation,HOUSEHOLD_1_444,HOUSEHOLD_1,HOUSEHOLD,CA_1,CA,d_1912,0,2016-04-23,11613,4.88,2016,4,5,1,2.0
1912999,HOUSEHOLD_1_444_CA_1_validation,HOUSEHOLD_1_444,HOUSEHOLD_1,HOUSEHOLD,CA_1,CA,d_1913,0,2016-04-24,11613,4.88,2016,4,6,1,0.0

In [63]:
#Inspect one product-store series
df[(df["item_id"]=="HOBBIES_1_001") &(df["store_id"] == "CA_1")][
    ["date", "sales", "sales_lag_1"]
].head(15)

         date  sales  sales_lag_1
0  2011-01-29      0          NaN
1  2011-01-30      0          0.0
2  2011-01-31      0          0.0
3  2011-02-01      0          0.0
4  2011-02-02      0          0.0
5  2011-02-03      0          0.0
6  2011-02-04      0          0.0
7  2011-02-05      0          0.0
8  2011-02-06      0          0.0
9  2011-02-07      0          0.0
10 2011-02-08      0          0.0
11 2011-02-09      0          0.0
12 2011-02-10      0          0.0
13 2011-02-11      0          0.0
14 2011-02-12      0          0.0

In [64]:
check = df[
    (df["item_id"] == "HOBBIES_1_001") &
    (df["store_id"] == "CA_1")
].copy()

check["expected_lag_1"] = check["sales"].shift(1)

(check["sales_lag_1"] == check["expected_lag_1"]).iloc[1:].all()

True

In [65]:
df["sales_lag_7"] = (
    df
    .groupby(["item_id", "store_id"])["sales"]
    .shift(7)
)

df["sales_lag_28"] = (
    df
    .groupby(["item_id", "store_id"])["sales"]
    .shift(28)
)

In [66]:
df[
    (df["item_id"] == "HOBBIES_1_001") &
    (df["store_id"] == "CA_1")
][
    ["date", "sales", "sales_lag_1", "sales_lag_7", "sales_lag_28"]
].head(35)

         date  sales  sales_lag_1  sales_lag_7  sales_lag_28
0  2011-01-29      0          NaN          NaN           NaN
1  2011-01-30      0          0.0          NaN           NaN
2  2011-01-31      0          0.0          NaN           NaN
3  2011-02-01      0          0.0          NaN           NaN
4  2011-02-02      0          0.0          NaN           NaN
5  2011-02-03      0          0.0          NaN           NaN
6  2011-02-04      0          0.0          NaN           NaN
7  2011-02-05      0          0.0          0.0           NaN
8  2011-02-06      0          0.0          0.0           NaN
9  2011-02-07      0          0.0          0.0           NaN
10 2011-02-08      0          0.0          0.0           NaN
11 2011-02-09      0          0.0          0.0           NaN
12 2011-02-10      0          0.0          0.0           NaN
13 2011-02-11      0          0.0          0.0           NaN
14 2011-02-12      0          0.0          0.0           NaN
15 2011-02-13      0          0.0          0.0           NaN
16 2011-02-14      0          0.0          0.0           NaN
17 2011-02-15      0          0.0          0.0           NaN
18 2011-02-16      0          0.0          0.0           NaN
19 2011-02-17      0          0.0          0.0           NaN
20 2011-02-18      0          0.0          0.0           NaN
21 2011-02-19      0          0.0          0.0           NaN
22 2011-02-20      0          0.0          0.0           NaN
23 2011-02-21      0          0.0          0.0           NaN
24 2011-02-22      0          0.0          0.0           NaN
25 2011-02-23      0          0.0          0.0           NaN
26 2011-02-24      0          0.0          0.0           NaN
27 2011-02-25      0          0.0          0.0           NaN
28 2011-02-26      0          0.0          0.0           0.0
29 2011-02-27      0          0.0          0.0           0.0
30 2011-02-28      0          0.0          0.0           0.0
31 2011-03-01      0          0.0          0.0           0.0
32 2011-03-02      0          0.0          0.0           0.0
33 2011-03-03      0          0.0          0.0           0.0
34 2011-03-04      0          0.0          0.0           0.0

#now we will create rolling feature
Meaning:

Average sales over the previous 7 days.

The logic is:

sales
  ↓
group by product + store
  ↓
shift(1)
  ↓
rolling 7-day mean

In [67]:
df["rolling_mean_7"] = (
    df
    .groupby(["item_id", "store_id"])["sales"]
    .transform(lambda x: x.shift(1).rolling(7).mean())
)
# we have used the shift because we dont want to include todays sales in 
# the average

In [68]:
df[
    (df["item_id"] == "HOBBIES_1_001") &
    (df["store_id"] == "CA_1")
][[
        "date",
        "sales",
        "sales_lag_1",
        "sales_lag_7",
        "sales_lag_28",
        "rolling_mean_7"]
].head(15)

         date  sales  sales_lag_1  sales_lag_7  sales_lag_28  rolling_mean_7
0  2011-01-29      0          NaN          NaN           NaN             NaN
1  2011-01-30      0          0.0          NaN           NaN             NaN
2  2011-01-31      0          0.0          NaN           NaN             NaN
3  2011-02-01      0          0.0          NaN           NaN             NaN
4  2011-02-02      0          0.0          NaN           NaN             NaN
5  2011-02-03      0          0.0          NaN           NaN             NaN
6  2011-02-04      0          0.0          NaN           NaN             NaN
7  2011-02-05      0          0.0          0.0           NaN             0.0
8  2011-02-06      0          0.0          0.0           NaN             0.0
9  2011-02-07      0          0.0          0.0           NaN             0.0
10 2011-02-08      0          0.0          0.0           NaN             0.0
11 2011-02-09      0          0.0          0.0           NaN             0.0
12 2011-02-10      0          0.0          0.0           NaN             0.0
13 2011-02-11      0          0.0          0.0           NaN             0.0
14 2011-02-12      0          0.0          0.0           NaN             0.0

In [69]:
df["rolling_mean_28"] = (
    df
    .groupby(["item_id", "store_id"])["sales"]
    .transform(lambda x: x.shift(1).rolling(28).mean())
)

In [70]:
#lets inspect the rolling_mean features 
df[
    (df["item_id"] == "HOBBIES_1_001") &
    (df["store_id"] == "CA_1")
][
    [
        "date",
        "sales",
        "sales_lag_1",
        "sales_lag_7",
        "sales_lag_28",
        "rolling_mean_7",
        "rolling_mean_28"
    ]
].head(35)

,date,sales,sales_lag_1,sales_lag_7,sales_lag_28,rolling_mean_7,rolling_mean_28
0,2011-01-29,0,NaN,NaN,NaN,NaN,NaN
1,2011-01-30,0,0.0,NaN,NaN,NaN,NaN
2,2011-01-31,0,0.0,NaN,NaN,NaN,NaN
3,2011-02-01,0,0.0,NaN,NaN,NaN,NaN
4,2011-02-02,0,0.0,NaN,NaN,NaN,NaN
5,2011-02-03,0,0.0,NaN,NaN,NaN,NaN
6,2011-02-04,0,0.0,NaN,NaN,NaN,NaN
7,2011-02-05,0,0.0,0.0,NaN,0.0,NaN
8,2011-02-06,0,0.0,0.0,NaN,0.0,NaN
9,2011-02-07,0,0.0,0.0,NaN,0.0,NaN
10,2011-02-08,0,0.0,0.0,NaN,0.0,NaN
11,2011-02-09,0,0.0,0.0,NaN,0.0,NaN
12,2011-02-10,0,0.0,0.0,NaN,0.0,NaN
13,2011-02-11,0,0.0,0.0,NaN,0.0,NaN
14,2011-02-12,0,0.0,0.0,NaN,0.0,NaN
15,2011-02-13,0,0.0,0.0,NaN,0.0,NaN
16,2011-02-14,0,0.0,0.0,NaN,0.0,NaN
17,2011-02-15,0,0.0,0.0,NaN,0.0,NaN
18,2011-02-16,0,0.0,0.0,NaN,0.0,NaN
19,2011-02-17,0,0.0,0.0,NaN,0.0,NaN
20,2011-02-18,0,0.0,0.0,NaN,0.0,NaN
21,2011-02-19,0,0.0,0.0,NaN,0.0,NaN
22,2011-02-20,0,0.0,0.0,NaN,0.0,NaN
23,2011-02-21,0,0.0,0.0,NaN,0.0,NaN
24,2011-02-22,0,0.0,0.0,NaN,0.0,NaN
25,2011-02-23,0,0.0,0.0,NaN,0.0,NaN
26,2011-02-24,0,0.0,0.0,NaN,0.0,NaN
27,2011-02-25,0,0.0,0.0,NaN,0.0,NaN
28,2011-02-26,0,0.0,0.0,0.0,0.0,0.0
29,2011-02-27,0,0.0,0.0,0.0,0.0,0.0
30,2011-02-28,0,0.0,0.0,0.0,0.0,0.0
31,2011-03-01,0,0.0,0.0,0.0,0.0,0.0
32,2011-03-02,0,0.0,0.0,0.0,0.0,0.0
33,2011-03-03,0,0.0,0.0,0.0,0.0,0.0
34,2011-03-04,0,0.0,0.0,0.0,0.0,0.0

# let's validate the rolling feature mathematically

In [71]:
check = df[
    (df["item_id"] == "HOBBIES_1_001") &
    (df["store_id"] == "CA_1")
].sort_values("date").reset_index(drop=True)

check[
    [
        "date",
        "sales",
        "sales_lag_1",
        "rolling_mean_7"
    ]
].iloc[1127:1145]

           date  sales  sales_lag_1  rolling_mean_7
1127 2014-03-01      1          0.0        0.428571
1128 2014-03-02      0          1.0        0.285714
1129 2014-03-03      0          0.0        0.285714
1130 2014-03-04      1          0.0        0.285714
1131 2014-03-05      0          1.0        0.285714
1132 2014-03-06      0          0.0        0.285714
1133 2014-03-07      0          0.0        0.285714
1134 2014-03-08      0          0.0        0.285714
1135 2014-03-09      1          0.0        0.142857
1136 2014-03-10      0          1.0        0.285714
1137 2014-03-11      0          0.0        0.285714
1138 2014-03-12      0          0.0        0.142857
1139 2014-03-13      0          0.0        0.142857
1140 2014-03-14      0          0.0        0.142857
1141 2014-03-15      0          0.0        0.142857
1142 2014-03-16      1          0.0        0.142857
1143 2014-03-17      0          1.0        0.142857
1144 2014-03-18      1          0.0        0.142857

In [72]:
current_row = 1127
previous_7_sales = check.loc[
    current_row - 7:current_row - 1,
    "sales"
]
previous_7_sales

1120    2
1121    0
1122    0
1123    1
1124    0
1125    0
1126    0
Name: sales, dtype: int64

In [73]:
previous_7_sales.mean()

0.42857142857142855

In [74]:
check.loc[current_row, "rolling_mean_7"]# look at index 1127 the mean value is present

0.42857142857142855

Why are we doing this?
We're learning an important ML engineering habit:

Don't blindly trust a feature-engineering operation just because the code runs. Validate the output against a known calculation

Should we simply give the model today's sell_price, or should we also tell it whether the price changed compared with the previous week?

That leads us into price-change features and another important forecasting concept: making sure the price information would actually be known at prediction time.

First: Can we use today's price?

It depends on the forecasting scenario.

Suppose our system predicts demand for tomorrow at the end of today.

If tomorrow's selling price is already known/planned, then using tomorrow's price is legitimate.

If tomorrow's price is unknown, we cannot use it.

This is another form of data leakage / availability leakage.

For our first model, we'll keep things simple and use the observed sell_price as a feature, while documenting that this assumes the price is known at prediction time

In [75]:
#check the current price
df["sell_price"].isna().sum()

392504

In [76]:
df["sell_price"].isna().mean() * 100#For now, we'll retain the missing values.

20.51772085729221

But there's another useful feature we can create:
price_available
This tells the model whether a price observation exists

In [77]:
df["price_available"] = df["sell_price"].notna().astype(int)
df

,id,item_id,dept_id,cat_id,store_id,state_id,d,sales,date,wm_yr_wk,...,year,month,day_of_week,is_weekend,sales_lag_1,sales_lag_7,sales_lag_28,rolling_mean_7,rolling_mean_28,price_available
0,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,...,2011,1,5,1,NaN,NaN,NaN,NaN,NaN,0
1,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_2,0,2011-01-30,11101,...,2011,1,6,1,0.0,NaN,NaN,NaN,NaN,0
2,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_3,0,2011-01-31,11101,...,2011,1,0,0,0.0,NaN,NaN,NaN,NaN,0
3,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_4,0,2011-02-01,11101,...,2011,2,1,0,0.0,NaN,NaN,NaN,NaN,0
4,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_5,0,2011-02-02,11101,...,2011,2,2,0,0.0,NaN,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1912995,HOUSEHOLD_1_444_CA_1_validation,HOUSEHOLD_1_444,HOUSEHOLD_1,HOUSEHOLD,CA_1,CA,d_1909,0,2016-04-20,11612,...,2016,4,2,0,0.0,0.0,0.0,0.000000,0.321429,1
1912996,HOUSEHOLD_1_444_CA_1_validation,HOUSEHOLD_1_444,HOUSEHOLD_1,HOUSEHOLD,CA_1,CA,d_1910,2,2016-04-21,11612,...,2016,4,3,0,0.0,0.0,1.0,0.000000,0.321429,1
1912997,HOUSEHOLD_1_444_CA_1_validation,HOUSEHOLD_1_444,HOUSEHOLD_1,HOUSEHOLD,CA_1,CA,d_1911,2,2016-04-22,11612,...,2016,4,4,0,2.0,0.0,2.0,0.285714,0.357143,1
1912998,HOUSEHOLD_1_444_CA_1_validation,HOUSEHOLD_1_444,HOUSEHOLD_1,HOUSEHOLD,CA_1,CA,d_1912,0,2016-04-23,11613,...,2016,4,5,1,2.0,0.0,0.0,0.571429,0.357143,1
1912999,HOUSEHOLD_1_444_CA_1_validation,HOUSEHOLD_1_444,HOUSEHOLD_1,HOUSEHOLD,CA_1,CA,d_1913,0,2016-04-24,11613,...,2016,4,6,1,0.0,0.0,3.0,0.571429,0.357143,1

In [78]:
'''
This preserves two separate pieces of information:

sell_price → what price was recorded
price_available → whether a price was recorded'''

'\nThis preserves two separate pieces of information:\n\nsell_price → what price was recorded\nprice_available → whether a price was recorded'

In [79]:
# now creating the feature for price change
df = df.sort_values(
    ["item_id", "store_id", "date"]
).reset_index(drop=True)

In [81]:
df["price_change"] = (
    df
    .groupby(["item_id", "store_id"])["sell_price"]
    .diff()
)
df

,id,item_id,dept_id,cat_id,store_id,state_id,d,sales,date,wm_yr_wk,...,month,day_of_week,is_weekend,sales_lag_1,sales_lag_7,sales_lag_28,rolling_mean_7,rolling_mean_28,price_available,price_change
0,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,...,1,5,1,NaN,NaN,NaN,NaN,NaN,0,NaN
1,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_2,0,2011-01-30,11101,...,1,6,1,0.0,NaN,NaN,NaN,NaN,0,NaN
2,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_3,0,2011-01-31,11101,...,1,0,0,0.0,NaN,NaN,NaN,NaN,0,NaN
3,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_4,0,2011-02-01,11101,...,2,1,0,0.0,NaN,NaN,NaN,NaN,0,NaN
4,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_5,0,2011-02-02,11101,...,2,2,0,0.0,NaN,NaN,NaN,NaN,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1912995,HOUSEHOLD_1_444_CA_1_validation,HOUSEHOLD_1_444,HOUSEHOLD_1,HOUSEHOLD,CA_1,CA,d_1909,0,2016-04-20,11612,...,4,2,0,0.0,0.0,0.0,0.000000,0.321429,1,0.0
1912996,HOUSEHOLD_1_444_CA_1_validation,HOUSEHOLD_1_444,HOUSEHOLD_1,HOUSEHOLD,CA_1,CA,d_1910,2,2016-04-21,11612,...,4,3,0,0.0,0.0,1.0,0.000000,0.321429,1,0.0
1912997,HOUSEHOLD_1_444_CA_1_validation,HOUSEHOLD_1_444,HOUSEHOLD_1,HOUSEHOLD,CA_1,CA,d_1911,2,2016-04-22,11612,...,4,4,0,2.0,0.0,2.0,0.285714,0.357143,1,0.0
1912998,HOUSEHOLD_1_444_CA_1_validation,HOUSEHOLD_1_444,HOUSEHOLD_1,HOUSEHOLD,CA_1,CA,d_1912,0,2016-04-23,11613,...,4,5,1,2.0,0.0,0.0,0.571429,0.357143,1,0.0
1912999,HOUSEHOLD_1_444_CA_1_validation,HOUSEHOLD_1_444,HOUSEHOLD_1,HOUSEHOLD,CA_1,CA,d_1913,0,2016-04-24,11613,...,4,6,1,0.0,0.0,3.0,0.571429,0.357143,1,0.0

In [82]:
df[
    (df["item_id"] == "HOBBIES_1_001") &
    (df["store_id"] == "CA_1")
][
    [
        "date",
        "sell_price",
        "price_available",
        "price_change"
    ]
].tail(30)

           date  sell_price  price_available  price_change
1883 2016-03-26        8.26                1          0.00
1884 2016-03-27        8.26                1          0.00
1885 2016-03-28        8.26                1          0.00
1886 2016-03-29        8.26                1          0.00
1887 2016-03-30        8.26                1          0.00
1888 2016-03-31        8.26                1          0.00
1889 2016-04-01        8.26                1          0.00
1890 2016-04-02        8.26                1          0.00
1891 2016-04-03        8.26                1          0.00
1892 2016-04-04        8.26                1          0.00
1893 2016-04-05        8.26                1          0.00
1894 2016-04-06        8.26                1          0.00
1895 2016-04-07        8.26                1          0.00
1896 2016-04-08        8.26                1          0.00
1897 2016-04-09        8.38                1          0.12
1898 2016-04-10        8.38                1          0.00
1899 2016-04-11        8.38                1          0.00
1900 2016-04-12        8.38                1          0.00
1901 2016-04-13        8.38                1          0.00
1902 2016-04-14        8.38                1          0.00
1903 2016-04-15        8.38                1          0.00
1904 2016-04-16        8.38                1          0.00
1905 2016-04-17        8.38                1          0.00
1906 2016-04-18        8.38                1          0.00
1907 2016-04-19        8.38                1          0.00
1908 2016-04-20        8.38                1          0.00
1909 2016-04-21        8.38                1          0.00
1910 2016-04-22        8.38                1          0.00
1911 2016-04-23        8.38                1          0.00
1912 2016-04-24        8.38                1          0.00

In [83]:
#inspect the missing price transitions
price_check = df[
    (df["item_id"] == "HOBBIES_1_001") &
    (df["store_id"] == "CA_1")
][
    ["date", "sell_price", "price_available", "price_change"]
]

price_check[
    price_check["sell_price"].isna()
].head(20)

         date  sell_price  price_available  price_change
0  2011-01-29         NaN                0           NaN
1  2011-01-30         NaN                0           NaN
2  2011-01-31         NaN                0           NaN
3  2011-02-01         NaN                0           NaN
4  2011-02-02         NaN                0           NaN
5  2011-02-03         NaN                0           NaN
6  2011-02-04         NaN                0           NaN
7  2011-02-05         NaN                0           NaN
8  2011-02-06         NaN                0           NaN
9  2011-02-07         NaN                0           NaN
10 2011-02-08         NaN                0           NaN
11 2011-02-09         NaN                0           NaN
12 2011-02-10         NaN                0           NaN
13 2011-02-11         NaN                0           NaN
14 2011-02-12         NaN                0           NaN
15 2011-02-13         NaN                0           NaN
16 2011-02-14         NaN                0           NaN
17 2011-02-15         NaN                0           NaN
18 2011-02-16         NaN                0           NaN
19 2011-02-17         NaN                0           NaN

In [86]:
df["price_changed"] = df["price_change"].ne(0).astype("Int64")
df[
    (df["item_id"] == "HOBBIES_1_001") &
    (df["store_id"] == "CA_1")
][
    [
        "date",
        "sell_price",
        "price_change",
        "price_changed"
    ]
].tail(30)

           date  sell_price  price_change  price_changed
1883 2016-03-26        8.26          0.00              0
1884 2016-03-27        8.26          0.00              0
1885 2016-03-28        8.26          0.00              0
1886 2016-03-29        8.26          0.00              0
1887 2016-03-30        8.26          0.00              0
1888 2016-03-31        8.26          0.00              0
1889 2016-04-01        8.26          0.00              0
1890 2016-04-02        8.26          0.00              0
1891 2016-04-03        8.26          0.00              0
1892 2016-04-04        8.26          0.00              0
1893 2016-04-05        8.26          0.00              0
1894 2016-04-06        8.26          0.00              0
1895 2016-04-07        8.26          0.00              0
1896 2016-04-08        8.26          0.00              0
1897 2016-04-09        8.38          0.12              1
1898 2016-04-10        8.38          0.00              0
1899 2016-04-11        8.38          0.00              0
1900 2016-04-12        8.38          0.00              0
1901 2016-04-13        8.38          0.00              0
1902 2016-04-14        8.38          0.00              0
1903 2016-04-15        8.38          0.00              0
1904 2016-04-16        8.38          0.00              0
1905 2016-04-17        8.38          0.00              0
1906 2016-04-18        8.38          0.00              0
1907 2016-04-19        8.38          0.00              0
1908 2016-04-20        8.38          0.00              0
1909 2016-04-21        8.38          0.00              0
1910 2016-04-22        8.38          0.00              0
1911 2016-04-23        8.38          0.00              0
1912 2016-04-24        8.38          0.00              0