In this notebook we will create additional information basically we will perform feature engineering

In [81]:
import pandas as pd
import datetime as dt
df = pd.read_parquet(
    "../data/processed/analytical_sample.parquet"
)

df.head()

,id,item_id,dept_id,cat_id,store_id,state_id,d,sales,date,wm_yr_wk,...,month,year,event_name_1,event_type_1,event_name_2,event_type_2,snap_CA,snap_TX,snap_WI,sell_price
0,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,...,1,2011,None,None,None,None,0,0,0,NaN
1,HOBBIES_1_002_CA_1_validation,HOBBIES_1_002,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,...,1,2011,None,None,None,None,0,0,0,NaN
2,HOBBIES_1_003_CA_1_validation,HOBBIES_1_003,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,...,1,2011,None,None,None,None,0,0,0,NaN
3,HOBBIES_1_004_CA_1_validation,HOBBIES_1_004,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,...,1,2011,None,None,None,None,0,0,0,NaN
4,HOBBIES_1_005_CA_1_validation,HOBBIES_1_005,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,...,1,2011,None,None,None,None,0,0,0,NaN

In [82]:
df.shape

(1913000, 22)

In [83]:
df["year"]=df["date"].dt.year
df

,id,item_id,dept_id,cat_id,store_id,state_id,d,sales,date,wm_yr_wk,...,month,year,event_name_1,event_type_1,event_name_2,event_type_2,snap_CA,snap_TX,snap_WI,sell_price
0,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,...,1,2011,None,None,None,None,0,0,0,NaN
1,HOBBIES_1_002_CA_1_validation,HOBBIES_1_002,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,...,1,2011,None,None,None,None,0,0,0,NaN
2,HOBBIES_1_003_CA_1_validation,HOBBIES_1_003,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,...,1,2011,None,None,None,None,0,0,0,NaN
3,HOBBIES_1_004_CA_1_validation,HOBBIES_1_004,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,...,1,2011,None,None,None,None,0,0,0,NaN
4,HOBBIES_1_005_CA_1_validation,HOBBIES_1_005,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,...,1,2011,None,None,None,None,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1912995,HOUSEHOLD_1_440_CA_1_validation,HOUSEHOLD_1_440,HOUSEHOLD_1,HOUSEHOLD,CA_1,CA,d_1913,1,2016-04-24,11613,...,4,2016,None,None,None,None,0,0,0,14.97
1912996,HOUSEHOLD_1_441_CA_1_validation,HOUSEHOLD_1_441,HOUSEHOLD_1,HOUSEHOLD,CA_1,CA,d_1913,5,2016-04-24,11613,...,4,2016,None,None,None,None,0,0,0,2.77
1912997,HOUSEHOLD_1_442_CA_1_validation,HOUSEHOLD_1_442,HOUSEHOLD_1,HOUSEHOLD,CA_1,CA,d_1913,0,2016-04-24,11613,...,4,2016,None,None,None,None,0,0,0,8.97
1912998,HOUSEHOLD_1_443_CA_1_validation,HOUSEHOLD_1_443,HOUSEHOLD_1,HOUSEHOLD,CA_1,CA,d_1913,0,2016-04-24,11613,...,4,2016,None,None,None,None,0,0,0,2.47
1912999,HOUSEHOLD_1_444_CA_1_validation,HOUSEHOLD_1_444,HOUSEHOLD_1,HOUSEHOLD,CA_1,CA,d_1913,0,2016-04-24,11613,...,4,2016,None,None,None,None,0,0,0,4.88

In [84]:
#creating month
df["month"]=df["date"].dt.month
df["day_of_week"]=df["date"].dt.dayofweek

In [85]:
#create a feature to check whether the date is weekend date or not
df["is_weekend"] = (df["day_of_week"] >= 5).astype(int)

In [86]:
# checking the new features with dates
df[
    [
        "date",
        "year",
        "month",
        "day_of_week",
        "is_weekend"
    ]
].sample(15)

              date  year  month  day_of_week  is_weekend
1570271 2015-05-18  2015      5            0           0
1600392 2015-06-17  2015      6            2           0
1460023 2015-01-28  2015      1            2           0
1717661 2015-10-12  2015     10            0           0
1816451 2016-01-19  2016      1            1           0
605502  2012-09-25  2012      9            1           0
1743062 2015-11-07  2015     11            5           1
880998  2013-06-27  2013      6            3           0
1680963 2015-09-05  2015      9            5           1
1573154 2015-05-21  2015      5            3           0
1514601 2015-03-23  2015      3            0           0
1835460 2016-02-07  2016      2            6           1
443912  2012-04-16  2012      4            0           0
1137577 2014-03-11  2014      3            1           0
35034   2011-03-05  2011      3            5           1

# now lets create the lag features for extracting the previous sales unit sold

Our data contains many different product-store series:

HOBBIES_1_001 + CA_1
HOBBIES_1_001 + CA_2
HOBBIES_1_002 + CA_1
...

We must not calculate one global lag.

For example, this would be wrong:

Product A, CA_1 → Apr 10 sales
Product B, CA_1 → Apr 11 sales

Product B's previous row isn't necessarily Product A's previous day.

Instead, we calculate the lag within each product-store group.


Product A + Store A

Jan 1
Jan 2
Jan 3
Jan 4 not a random order

In [87]:
# sort the data so that future sales not come before
#Because shift() works according to row order.
df = df.sort_values(
    ["item_id", "store_id", "date"]
).reset_index(drop=True)

In [88]:
df

,id,item_id,dept_id,cat_id,store_id,state_id,d,sales,date,wm_yr_wk,...,event_name_1,event_type_1,event_name_2,event_type_2,snap_CA,snap_TX,snap_WI,sell_price,day_of_week,is_weekend
0,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,...,None,None,None,None,0,0,0,NaN,5,1
1,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_2,0,2011-01-30,11101,...,None,None,None,None,0,0,0,NaN,6,1
2,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_3,0,2011-01-31,11101,...,None,None,None,None,0,0,0,NaN,0,0
3,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_4,0,2011-02-01,11101,...,None,None,None,None,1,1,0,NaN,1,0
4,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_5,0,2011-02-02,11101,...,None,None,None,None,1,0,1,NaN,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1912995,HOUSEHOLD_1_444_CA_1_validation,HOUSEHOLD_1_444,HOUSEHOLD_1,HOUSEHOLD,CA_1,CA,d_1909,0,2016-04-20,11612,...,None,None,None,None,0,0,0,4.88,2,0
1912996,HOUSEHOLD_1_444_CA_1_validation,HOUSEHOLD_1_444,HOUSEHOLD_1,HOUSEHOLD,CA_1,CA,d_1910,2,2016-04-21,11612,...,None,None,None,None,0,0,0,4.88,3,0
1912997,HOUSEHOLD_1_444_CA_1_validation,HOUSEHOLD_1_444,HOUSEHOLD_1,HOUSEHOLD,CA_1,CA,d_1911,2,2016-04-22,11612,...,None,None,None,None,0,0,0,4.88,4,0
1912998,HOUSEHOLD_1_444_CA_1_validation,HOUSEHOLD_1_444,HOUSEHOLD_1,HOUSEHOLD,CA_1,CA,d_1912,0,2016-04-23,11613,...,None,None,None,None,0,0,0,4.88,5,1
1912999,HOUSEHOLD_1_444_CA_1_validation,HOUSEHOLD_1_444,HOUSEHOLD_1,HOUSEHOLD,CA_1,CA,d_1913,0,2016-04-24,11613,...,None,None,None,None,0,0,0,4.88,6,1

In [89]:
df["sales_lag_1"] = (
    df
    .groupby(["item_id", "store_id"])["sales"]
    .shift(1)
)
# we are just doing  group the data and then take sales then lag or shift

Separate the data into individual product-store time series.
groupby(["item_id", "store_id"])
Take:-
df["sales"]

then .shift(1) Move the previous sales value down by one row.

In [90]:
df

,id,item_id,dept_id,cat_id,store_id,state_id,d,sales,date,wm_yr_wk,...,event_type_1,event_name_2,event_type_2,snap_CA,snap_TX,snap_WI,sell_price,day_of_week,is_weekend,sales_lag_1
0,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,...,None,None,None,0,0,0,NaN,5,1,NaN
1,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_2,0,2011-01-30,11101,...,None,None,None,0,0,0,NaN,6,1,0.0
2,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_3,0,2011-01-31,11101,...,None,None,None,0,0,0,NaN,0,0,0.0
3,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_4,0,2011-02-01,11101,...,None,None,None,1,1,0,NaN,1,0,0.0
4,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_5,0,2011-02-02,11101,...,None,None,None,1,0,1,NaN,2,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1912995,HOUSEHOLD_1_444_CA_1_validation,HOUSEHOLD_1_444,HOUSEHOLD_1,HOUSEHOLD,CA_1,CA,d_1909,0,2016-04-20,11612,...,None,None,None,0,0,0,4.88,2,0,0.0
1912996,HOUSEHOLD_1_444_CA_1_validation,HOUSEHOLD_1_444,HOUSEHOLD_1,HOUSEHOLD,CA_1,CA,d_1910,2,2016-04-21,11612,...,None,None,None,0,0,0,4.88,3,0,0.0
1912997,HOUSEHOLD_1_444_CA_1_validation,HOUSEHOLD_1_444,HOUSEHOLD_1,HOUSEHOLD,CA_1,CA,d_1911,2,2016-04-22,11612,...,None,None,None,0,0,0,4.88,4,0,2.0
1912998,HOUSEHOLD_1_444_CA_1_validation,HOUSEHOLD_1_444,HOUSEHOLD_1,HOUSEHOLD,CA_1,CA,d_1912,0,2016-04-23,11613,...,None,None,None,0,0,0,4.88,5,1,2.0
1912999,HOUSEHOLD_1_444_CA_1_validation,HOUSEHOLD_1_444,HOUSEHOLD_1,HOUSEHOLD,CA_1,CA,d_1913,0,2016-04-24,11613,...,None,None,None,0,0,0,4.88,6,1,0.0

In [91]:
#Inspect one product-store series
df[(df["item_id"]=="HOBBIES_1_001") &(df["store_id"] == "CA_1")][
    ["date", "sales", "sales_lag_1"]
].head(15)

         date  sales  sales_lag_1
0  2011-01-29      0          NaN
1  2011-01-30      0          0.0
2  2011-01-31      0          0.0
3  2011-02-01      0          0.0
4  2011-02-02      0          0.0
5  2011-02-03      0          0.0
6  2011-02-04      0          0.0
7  2011-02-05      0          0.0
8  2011-02-06      0          0.0
9  2011-02-07      0          0.0
10 2011-02-08      0          0.0
11 2011-02-09      0          0.0
12 2011-02-10      0          0.0
13 2011-02-11      0          0.0
14 2011-02-12      0          0.0

In [92]:
check = df[
    (df["item_id"] == "HOBBIES_1_001") &
    (df["store_id"] == "CA_1")
].copy()

check["expected_lag_1"] = check["sales"].shift(1)

(check["sales_lag_1"] == check["expected_lag_1"]).iloc[1:].all()

True

In [93]:
df["sales_lag_7"] = (
    df
    .groupby(["item_id", "store_id"])["sales"]
    .shift(7)
)

df["sales_lag_28"] = (
    df
    .groupby(["item_id", "store_id"])["sales"]
    .shift(28)
)

In [94]:
df[
    (df["item_id"] == "HOBBIES_1_001") &
    (df["store_id"] == "CA_1")
][
    ["date", "sales", "sales_lag_1", "sales_lag_7", "sales_lag_28"]
].head(35)

         date  sales  sales_lag_1  sales_lag_7  sales_lag_28
0  2011-01-29      0          NaN          NaN           NaN
1  2011-01-30      0          0.0          NaN           NaN
2  2011-01-31      0          0.0          NaN           NaN
3  2011-02-01      0          0.0          NaN           NaN
4  2011-02-02      0          0.0          NaN           NaN
5  2011-02-03      0          0.0          NaN           NaN
6  2011-02-04      0          0.0          NaN           NaN
7  2011-02-05      0          0.0          0.0           NaN
8  2011-02-06      0          0.0          0.0           NaN
9  2011-02-07      0          0.0          0.0           NaN
10 2011-02-08      0          0.0          0.0           NaN
11 2011-02-09      0          0.0          0.0           NaN
12 2011-02-10      0          0.0          0.0           NaN
13 2011-02-11      0          0.0          0.0           NaN
14 2011-02-12      0          0.0          0.0           NaN
15 2011-02-13      0          0.0          0.0           NaN
16 2011-02-14      0          0.0          0.0           NaN
17 2011-02-15      0          0.0          0.0           NaN
18 2011-02-16      0          0.0          0.0           NaN
19 2011-02-17      0          0.0          0.0           NaN
20 2011-02-18      0          0.0          0.0           NaN
21 2011-02-19      0          0.0          0.0           NaN
22 2011-02-20      0          0.0          0.0           NaN
23 2011-02-21      0          0.0          0.0           NaN
24 2011-02-22      0          0.0          0.0           NaN
25 2011-02-23      0          0.0          0.0           NaN
26 2011-02-24      0          0.0          0.0           NaN
27 2011-02-25      0          0.0          0.0           NaN
28 2011-02-26      0          0.0          0.0           0.0
29 2011-02-27      0          0.0          0.0           0.0
30 2011-02-28      0          0.0          0.0           0.0
31 2011-03-01      0          0.0          0.0           0.0
32 2011-03-02      0          0.0          0.0           0.0
33 2011-03-03      0          0.0          0.0           0.0
34 2011-03-04      0          0.0          0.0           0.0

#now we will create rolling feature
Meaning:

Average sales over the previous 7 days.

The logic is:

sales
  ↓
group by product + store
  ↓
shift(1)
  ↓
rolling 7-day mean

In [95]:
df["rolling_mean_7"] = (
    df
    .groupby(["item_id", "store_id"])["sales"]
    .transform(lambda x: x.shift(1).rolling(7).mean())
)
# we have used the shift because we dont want to include todays sales in 
# the average

In [96]:
df[
    (df["item_id"] == "HOBBIES_1_001") &
    (df["store_id"] == "CA_1")
][[
        "date",
        "sales",
        "sales_lag_1",
        "sales_lag_7",
        "sales_lag_28",
        "rolling_mean_7"]
].head(15)

         date  sales  sales_lag_1  sales_lag_7  sales_lag_28  rolling_mean_7
0  2011-01-29      0          NaN          NaN           NaN             NaN
1  2011-01-30      0          0.0          NaN           NaN             NaN
2  2011-01-31      0          0.0          NaN           NaN             NaN
3  2011-02-01      0          0.0          NaN           NaN             NaN
4  2011-02-02      0          0.0          NaN           NaN             NaN
5  2011-02-03      0          0.0          NaN           NaN             NaN
6  2011-02-04      0          0.0          NaN           NaN             NaN
7  2011-02-05      0          0.0          0.0           NaN             0.0
8  2011-02-06      0          0.0          0.0           NaN             0.0
9  2011-02-07      0          0.0          0.0           NaN             0.0
10 2011-02-08      0          0.0          0.0           NaN             0.0
11 2011-02-09      0          0.0          0.0           NaN             0.0
12 2011-02-10      0          0.0          0.0           NaN             0.0
13 2011-02-11      0          0.0          0.0           NaN             0.0
14 2011-02-12      0          0.0          0.0           NaN             0.0

In [97]:
df["rolling_mean_28"] = (
    df
    .groupby(["item_id", "store_id"])["sales"]
    .transform(lambda x: x.shift(1).rolling(28).mean())
)

In [98]:
#lets inspect the rolling_mean features 
df[
    (df["item_id"] == "HOBBIES_1_001") &
    (df["store_id"] == "CA_1")
][
    [
        "date",
        "sales",
        "sales_lag_1",
        "sales_lag_7",
        "sales_lag_28",
        "rolling_mean_7",
        "rolling_mean_28"
    ]
].head(35)

,date,sales,sales_lag_1,sales_lag_7,sales_lag_28,rolling_mean_7,rolling_mean_28
0,2011-01-29,0,NaN,NaN,NaN,NaN,NaN
1,2011-01-30,0,0.0,NaN,NaN,NaN,NaN
2,2011-01-31,0,0.0,NaN,NaN,NaN,NaN
3,2011-02-01,0,0.0,NaN,NaN,NaN,NaN
4,2011-02-02,0,0.0,NaN,NaN,NaN,NaN
5,2011-02-03,0,0.0,NaN,NaN,NaN,NaN
6,2011-02-04,0,0.0,NaN,NaN,NaN,NaN
7,2011-02-05,0,0.0,0.0,NaN,0.0,NaN
8,2011-02-06,0,0.0,0.0,NaN,0.0,NaN
9,2011-02-07,0,0.0,0.0,NaN,0.0,NaN
10,2011-02-08,0,0.0,0.0,NaN,0.0,NaN
11,2011-02-09,0,0.0,0.0,NaN,0.0,NaN
12,2011-02-10,0,0.0,0.0,NaN,0.0,NaN
13,2011-02-11,0,0.0,0.0,NaN,0.0,NaN
14,2011-02-12,0,0.0,0.0,NaN,0.0,NaN
15,2011-02-13,0,0.0,0.0,NaN,0.0,NaN
16,2011-02-14,0,0.0,0.0,NaN,0.0,NaN
17,2011-02-15,0,0.0,0.0,NaN,0.0,NaN
18,2011-02-16,0,0.0,0.0,NaN,0.0,NaN
19,2011-02-17,0,0.0,0.0,NaN,0.0,NaN
20,2011-02-18,0,0.0,0.0,NaN,0.0,NaN
21,2011-02-19,0,0.0,0.0,NaN,0.0,NaN
22,2011-02-20,0,0.0,0.0,NaN,0.0,NaN
23,2011-02-21,0,0.0,0.0,NaN,0.0,NaN
24,2011-02-22,0,0.0,0.0,NaN,0.0,NaN
25,2011-02-23,0,0.0,0.0,NaN,0.0,NaN
26,2011-02-24,0,0.0,0.0,NaN,0.0,NaN
27,2011-02-25,0,0.0,0.0,NaN,0.0,NaN
28,2011-02-26,0,0.0,0.0,0.0,0.0,0.0
29,2011-02-27,0,0.0,0.0,0.0,0.0,0.0
30,2011-02-28,0,0.0,0.0,0.0,0.0,0.0
31,2011-03-01,0,0.0,0.0,0.0,0.0,0.0
32,2011-03-02,0,0.0,0.0,0.0,0.0,0.0
33,2011-03-03,0,0.0,0.0,0.0,0.0,0.0
34,2011-03-04,0,0.0,0.0,0.0,0.0,0.0

# let's validate the rolling feature mathematically

In [99]:
check = df[
    (df["item_id"] == "HOBBIES_1_001") &
    (df["store_id"] == "CA_1")
].sort_values("date").reset_index(drop=True)

check[
    [
        "date",
        "sales",
        "sales_lag_1",
        "rolling_mean_7"
    ]
].iloc[1127:1145]

           date  sales  sales_lag_1  rolling_mean_7
1127 2014-03-01      1          0.0        0.428571
1128 2014-03-02      0          1.0        0.285714
1129 2014-03-03      0          0.0        0.285714
1130 2014-03-04      1          0.0        0.285714
1131 2014-03-05      0          1.0        0.285714
1132 2014-03-06      0          0.0        0.285714
1133 2014-03-07      0          0.0        0.285714
1134 2014-03-08      0          0.0        0.285714
1135 2014-03-09      1          0.0        0.142857
1136 2014-03-10      0          1.0        0.285714
1137 2014-03-11      0          0.0        0.285714
1138 2014-03-12      0          0.0        0.142857
1139 2014-03-13      0          0.0        0.142857
1140 2014-03-14      0          0.0        0.142857
1141 2014-03-15      0          0.0        0.142857
1142 2014-03-16      1          0.0        0.142857
1143 2014-03-17      0          1.0        0.142857
1144 2014-03-18      1          0.0        0.142857

In [100]:
current_row = 1127
previous_7_sales = check.loc[
    current_row - 7:current_row - 1,
    "sales"
]
previous_7_sales

1120    2
1121    0
1122    0
1123    1
1124    0
1125    0
1126    0
Name: sales, dtype: int64

In [101]:
previous_7_sales.mean()

0.42857142857142855

In [102]:
check.loc[current_row, "rolling_mean_7"]# look at index 1127 the mean value is present

0.42857142857142855

Why are we doing this?
We're learning an important ML engineering habit:

Don't blindly trust a feature-engineering operation just because the code runs. Validate the output against a known calculation

Should we simply give the model today's sell_price, or should we also tell it whether the price changed compared with the previous week?

That leads us into price-change features and another important forecasting concept: making sure the price information would actually be known at prediction time.

First: Can we use today's price?

It depends on the forecasting scenario.

Suppose our system predicts demand for tomorrow at the end of today.

If tomorrow's selling price is already known/planned, then using tomorrow's price is legitimate.

If tomorrow's price is unknown, we cannot use it.

This is another form of data leakage / availability leakage.

For our first model, we'll keep things simple and use the observed sell_price as a feature, while documenting that this assumes the price is known at prediction time

In [103]:
#check the current price
df["sell_price"].isna().sum()

392504

In [104]:
df["sell_price"].isna().mean() * 100#For now, we'll retain the missing values.

20.51772085729221

But there's another useful feature we can create:
price_available
This tells the model whether a price observation exists

In [105]:
df["price_available"] = df["sell_price"].notna().astype(int)
df

,id,item_id,dept_id,cat_id,store_id,state_id,d,sales,date,wm_yr_wk,...,snap_WI,sell_price,day_of_week,is_weekend,sales_lag_1,sales_lag_7,sales_lag_28,rolling_mean_7,rolling_mean_28,price_available
0,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,...,0,NaN,5,1,NaN,NaN,NaN,NaN,NaN,0
1,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_2,0,2011-01-30,11101,...,0,NaN,6,1,0.0,NaN,NaN,NaN,NaN,0
2,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_3,0,2011-01-31,11101,...,0,NaN,0,0,0.0,NaN,NaN,NaN,NaN,0
3,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_4,0,2011-02-01,11101,...,0,NaN,1,0,0.0,NaN,NaN,NaN,NaN,0
4,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_5,0,2011-02-02,11101,...,1,NaN,2,0,0.0,NaN,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1912995,HOUSEHOLD_1_444_CA_1_validation,HOUSEHOLD_1_444,HOUSEHOLD_1,HOUSEHOLD,CA_1,CA,d_1909,0,2016-04-20,11612,...,0,4.88,2,0,0.0,0.0,0.0,0.000000,0.321429,1
1912996,HOUSEHOLD_1_444_CA_1_validation,HOUSEHOLD_1_444,HOUSEHOLD_1,HOUSEHOLD,CA_1,CA,d_1910,2,2016-04-21,11612,...,0,4.88,3,0,0.0,0.0,1.0,0.000000,0.321429,1
1912997,HOUSEHOLD_1_444_CA_1_validation,HOUSEHOLD_1_444,HOUSEHOLD_1,HOUSEHOLD,CA_1,CA,d_1911,2,2016-04-22,11612,...,0,4.88,4,0,2.0,0.0,2.0,0.285714,0.357143,1
1912998,HOUSEHOLD_1_444_CA_1_validation,HOUSEHOLD_1_444,HOUSEHOLD_1,HOUSEHOLD,CA_1,CA,d_1912,0,2016-04-23,11613,...,0,4.88,5,1,2.0,0.0,0.0,0.571429,0.357143,1
1912999,HOUSEHOLD_1_444_CA_1_validation,HOUSEHOLD_1_444,HOUSEHOLD_1,HOUSEHOLD,CA_1,CA,d_1913,0,2016-04-24,11613,...,0,4.88,6,1,0.0,0.0,3.0,0.571429,0.357143,1

In [106]:
'''
This preserves two separate pieces of information:

sell_price → what price was recorded
price_available → whether a price was recorded'''

'\nThis preserves two separate pieces of information:\n\nsell_price → what price was recorded\nprice_available → whether a price was recorded'

In [107]:
# now creating the feature for price change
df = df.sort_values(
    ["item_id", "store_id", "date"]
).reset_index(drop=True)

In [108]:
df["price_change"] = (
    df
    .groupby(["item_id", "store_id"])["sell_price"]
    .diff()
)
df

,id,item_id,dept_id,cat_id,store_id,state_id,d,sales,date,wm_yr_wk,...,sell_price,day_of_week,is_weekend,sales_lag_1,sales_lag_7,sales_lag_28,rolling_mean_7,rolling_mean_28,price_available,price_change
0,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,...,NaN,5,1,NaN,NaN,NaN,NaN,NaN,0,NaN
1,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_2,0,2011-01-30,11101,...,NaN,6,1,0.0,NaN,NaN,NaN,NaN,0,NaN
2,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_3,0,2011-01-31,11101,...,NaN,0,0,0.0,NaN,NaN,NaN,NaN,0,NaN
3,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_4,0,2011-02-01,11101,...,NaN,1,0,0.0,NaN,NaN,NaN,NaN,0,NaN
4,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_5,0,2011-02-02,11101,...,NaN,2,0,0.0,NaN,NaN,NaN,NaN,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1912995,HOUSEHOLD_1_444_CA_1_validation,HOUSEHOLD_1_444,HOUSEHOLD_1,HOUSEHOLD,CA_1,CA,d_1909,0,2016-04-20,11612,...,4.88,2,0,0.0,0.0,0.0,0.000000,0.321429,1,0.0
1912996,HOUSEHOLD_1_444_CA_1_validation,HOUSEHOLD_1_444,HOUSEHOLD_1,HOUSEHOLD,CA_1,CA,d_1910,2,2016-04-21,11612,...,4.88,3,0,0.0,0.0,1.0,0.000000,0.321429,1,0.0
1912997,HOUSEHOLD_1_444_CA_1_validation,HOUSEHOLD_1_444,HOUSEHOLD_1,HOUSEHOLD,CA_1,CA,d_1911,2,2016-04-22,11612,...,4.88,4,0,2.0,0.0,2.0,0.285714,0.357143,1,0.0
1912998,HOUSEHOLD_1_444_CA_1_validation,HOUSEHOLD_1_444,HOUSEHOLD_1,HOUSEHOLD,CA_1,CA,d_1912,0,2016-04-23,11613,...,4.88,5,1,2.0,0.0,0.0,0.571429,0.357143,1,0.0
1912999,HOUSEHOLD_1_444_CA_1_validation,HOUSEHOLD_1_444,HOUSEHOLD_1,HOUSEHOLD,CA_1,CA,d_1913,0,2016-04-24,11613,...,4.88,6,1,0.0,0.0,3.0,0.571429,0.357143,1,0.0

In [109]:
df[
    (df["item_id"] == "HOBBIES_1_001") &
    (df["store_id"] == "CA_1")
][
    [
        "date",
        "sell_price",
        "price_available",
        "price_change"
    ]
].tail(30)

           date  sell_price  price_available  price_change
1883 2016-03-26        8.26                1          0.00
1884 2016-03-27        8.26                1          0.00
1885 2016-03-28        8.26                1          0.00
1886 2016-03-29        8.26                1          0.00
1887 2016-03-30        8.26                1          0.00
1888 2016-03-31        8.26                1          0.00
1889 2016-04-01        8.26                1          0.00
1890 2016-04-02        8.26                1          0.00
1891 2016-04-03        8.26                1          0.00
1892 2016-04-04        8.26                1          0.00
1893 2016-04-05        8.26                1          0.00
1894 2016-04-06        8.26                1          0.00
1895 2016-04-07        8.26                1          0.00
1896 2016-04-08        8.26                1          0.00
1897 2016-04-09        8.38                1          0.12
1898 2016-04-10        8.38                1          0.00
1899 2016-04-11        8.38                1          0.00
1900 2016-04-12        8.38                1          0.00
1901 2016-04-13        8.38                1          0.00
1902 2016-04-14        8.38                1          0.00
1903 2016-04-15        8.38                1          0.00
1904 2016-04-16        8.38                1          0.00
1905 2016-04-17        8.38                1          0.00
1906 2016-04-18        8.38                1          0.00
1907 2016-04-19        8.38                1          0.00
1908 2016-04-20        8.38                1          0.00
1909 2016-04-21        8.38                1          0.00
1910 2016-04-22        8.38                1          0.00
1911 2016-04-23        8.38                1          0.00
1912 2016-04-24        8.38                1          0.00

In [110]:
#inspect the missing price transitions
price_check = df[
    (df["item_id"] == "HOBBIES_1_001") &
    (df["store_id"] == "CA_1")
][
    ["date", "sell_price", "price_available", "price_change"]
]

price_check[
    price_check["sell_price"].isna()
].head(20)

         date  sell_price  price_available  price_change
0  2011-01-29         NaN                0           NaN
1  2011-01-30         NaN                0           NaN
2  2011-01-31         NaN                0           NaN
3  2011-02-01         NaN                0           NaN
4  2011-02-02         NaN                0           NaN
5  2011-02-03         NaN                0           NaN
6  2011-02-04         NaN                0           NaN
7  2011-02-05         NaN                0           NaN
8  2011-02-06         NaN                0           NaN
9  2011-02-07         NaN                0           NaN
10 2011-02-08         NaN                0           NaN
11 2011-02-09         NaN                0           NaN
12 2011-02-10         NaN                0           NaN
13 2011-02-11         NaN                0           NaN
14 2011-02-12         NaN                0           NaN
15 2011-02-13         NaN                0           NaN
16 2011-02-14         NaN                0           NaN
17 2011-02-15         NaN                0           NaN
18 2011-02-16         NaN                0           NaN
19 2011-02-17         NaN                0           NaN

In [111]:
df["price_changed"] = df["price_change"].ne(0).astype("Int64")
df[
    (df["item_id"] == "HOBBIES_1_001") &
    (df["store_id"] == "CA_1")
][
    [
        "date",
        "sell_price",
        "price_change",
        "price_changed"
    ]
].tail(30)

           date  sell_price  price_change  price_changed
1883 2016-03-26        8.26          0.00              0
1884 2016-03-27        8.26          0.00              0
1885 2016-03-28        8.26          0.00              0
1886 2016-03-29        8.26          0.00              0
1887 2016-03-30        8.26          0.00              0
1888 2016-03-31        8.26          0.00              0
1889 2016-04-01        8.26          0.00              0
1890 2016-04-02        8.26          0.00              0
1891 2016-04-03        8.26          0.00              0
1892 2016-04-04        8.26          0.00              0
1893 2016-04-05        8.26          0.00              0
1894 2016-04-06        8.26          0.00              0
1895 2016-04-07        8.26          0.00              0
1896 2016-04-08        8.26          0.00              0
1897 2016-04-09        8.38          0.12              1
1898 2016-04-10        8.38          0.00              0
1899 2016-04-11        8.38          0.00              0
1900 2016-04-12        8.38          0.00              0
1901 2016-04-13        8.38          0.00              0
1902 2016-04-14        8.38          0.00              0
1903 2016-04-15        8.38          0.00              0
1904 2016-04-16        8.38          0.00              0
1905 2016-04-17        8.38          0.00              0
1906 2016-04-18        8.38          0.00              0
1907 2016-04-19        8.38          0.00              0
1908 2016-04-20        8.38          0.00              0
1909 2016-04-21        8.38          0.00              0
1910 2016-04-22        8.38          0.00              0
1911 2016-04-23        8.38          0.00              0
1912 2016-04-24        8.38          0.00              0

Currently, our dataset knows when something happened through date, but it doesn't yet know useful contextual information such as:
Was it a weekend?
Was there an event?
Was SNAP active?

These can help the forecasting model understand demand patterns.
We donot need to change this notebook update in feature engineering one 

Understand SNAP
Before coding, this is an important M5 concept.
There are three columns:
snap_CA
snap_TX
snap_WI

They represent whether the SNAP program was active for that state on that date.
Our rows contain:
store_id → CA_1 / TX_1 / WI_1 ...
state_id → CA / TX / WI

Therefore, instead of giving the model three separate SNAP columns for every row, we can eventually create:
snap_active

based on the store's state.
For example:
CA_1 → use snap_CA
TX_1 → use snap_TX
WI_1 → use snap_WI

This is more meaningful for our model.
But don't code that yet.

In [112]:
#First let's inspect the actual event data.
df[
    ["event_name_1", "event_type_1", "event_name_2", "event_type_2"]
].notna().sum()

event_name_1    154000
event_type_1    154000
event_name_2      4000
event_type_2      4000
dtype: int64

Why are there so many event observations? 
Explanation:- Remember, we're tracking 1,000 product series. When an event occurs on a date, that calendar information is repeated across the corresponding product observations.
For example, Valentine's Day can appear for many different products because the event belongs to the date, not to one particular product.
Also, NaN in an event column generally means that no event is recorded for that event slot on that date. It doesn't automatically mean a data error.

In [113]:
df[
    ["event_name_1", "event_type_1", "event_name_2", "event_type_2"]
].dropna(how="all").head(20)

        event_name_1 event_type_1 event_name_2 event_type_2
8          SuperBowl     Sporting         None         None
16     ValentinesDay     Cultural         None         None
23     PresidentsDay     National         None         None
39         LentStart    Religious         None         None
46         LentWeek2    Religious         None         None
47     StPatricksDay     Cultural         None         None
50         Purim End    Religious         None         None
85    OrthodoxEaster    Religious       Easter     Cultural
87        Pesach End    Religious         None         None
96     Cinco De Mayo     Cultural         None         None
99      Mother's day     Cultural         None         None
121      MemorialDay     National         None         None
122   NBAFinalsStart     Sporting         None         None
134     NBAFinalsEnd     Sporting         None         None
141     Father's day     Cultural         None         None
156  IndependenceDay     National         None         None
184   Ramadan starts    Religious         None         None
214      Eid al-Fitr    Religious         None         None
219         LaborDay     National         None         None
254      ColumbusDay     National         None         None

Create an event indicator
First, let's create a simple binary feature called is_event.
Concept: Binary encoding represents a condition using 1 or 0.
- 1 — at least one event is recorded.
- 0 — neither event column contains an event.

In [114]:
df["is_event"] = (
    df[["event_name_1", "event_name_2"]]
    .notna()
    .any(axis=1)
    .astype("int8")
)

In [115]:
df['is_event'].value_counts()

is_event
0    1759000
1     154000
Name: count, dtype: int64

we have total 1913000 records right now but only 154000 event have been recorded in dataset 
Approximately 8.05% pf observations have a recorded event

In [116]:
#inspect a few event dates
df.loc[
    df["is_event"] == 1,
    ["date", "event_name_1", "event_name_2", "is_event"]
].head(10)

         date    event_name_1 event_name_2  is_event
8  2011-02-06       SuperBowl         None         1
16 2011-02-14   ValentinesDay         None         1
23 2011-02-21   PresidentsDay         None         1
39 2011-03-09       LentStart         None         1
46 2011-03-16       LentWeek2         None         1
47 2011-03-17   StPatricksDay         None         1
50 2011-03-20       Purim End         None         1
85 2011-04-24  OrthodoxEaster       Easter         1
87 2011-04-26      Pesach End         None         1
96 2011-05-05   Cinco De Mayo         None         1

# create snap_active feature
- our dataset contains three SNAP columns snap_ca,snap_TX,snap_WI
- Each relates to different state. Since each row already has a state_id,we can create one feature that selects the relevant state's Snap Indicator
- Important concept — Feature relevance: A feature should represent the information relevant to that particular observation.

In [117]:
df["state_id"].value_counts()#due to sample limitation we only have CA state_id now

state_id
CA    1913000
Name: count, dtype: int64

#for current sample we can safely create snap_active=snap_CA
Sample representativeness
A sample is useful for development, but its limitations must be understood before generalizing conclusions to the full dataset.

Our current sample represents:
CA
└── 1,000 product/store rows
    └── 1,913 days
it doesnot represent CA+TX+WI together

In [118]:
# step-1now moving towards actual forcasting problem
expected_features = [
    "sales_lag_1",
    "sales_lag_7",
    "sales_lag_28",
    "rolling_mean_7",
    "rolling_mean_28",
    "price_available",
    "price_change",
    "price_changed",
    "is_event"
]

available = [col for col in expected_features if col in df.columns]
missing = [col for col in expected_features if col not in df.columns]

print("Available features:", available)
print("Missing features:", missing)
'''
all columns are present in dataset 
'''

Available features: ['sales_lag_1', 'sales_lag_7', 'sales_lag_28', 'rolling_mean_7', 'rolling_mean_28', 'price_available', 'price_change', 'price_changed', 'is_event']
Missing features: []

'\nall columns are present in dataset \n'

#step-2 Understanding our forcasting target 
Our business question is:
Using historical sales and information known in advance, how many units of a product will a particular store sell on the next day?

We'll use a one-day-ahead demand forecast.
For example, suppose we're preparing a forecast for February 10:
Information	                   Value
Sales on February 9	            3
Sales seven days earlier	    2
Previous seven-day average	    2.4
Known event on February 10	    Yes
Target: sales on February 10	 ?
the model learns to predict the final value using information available before february10's sales occur 
for our setup "sales" will be the target column
Our lag and rolling features must use only past sales, while calendar information and any price used for forecasting must be available or known in advance.As we have done feature engineering in the same way

Important concept — Target leakage: If we accidentally give the model February 10's actual sales as an input while asking it to predict those same sales, the evaluation becomes invalid.

# Defining our forecasting model 
Our current lag features are aligned with the same date's sales. For a row dated February 10, for example:
- sales_lag_1 contains sales from February 9.
- sales_lag_7 contains sales from seven days earlier.
- rolling_mean_7 uses the previous seven days, excluding February 10.
- sales contains the actual sales on February 10.
Therefore, our forecasting problem is:
At the start of a day, predict that day's demand using historical sales and information available in advance.


One assumption for this project model : today's price must be known or planned before the forecast is made.

# Defining our input features 
Feature group	          Columns
Product information	      item_id, dept_id, cat_id, store_id, state_id
Time	                  year, month, day_of_week, is_weekend
Historical demand	      sales_lag_1, sales_lag_7, sales_lag_28
Demand trends	          rolling_mean_7, rolling_mean_28
Price	                  sell_price, price_available, price_change, price_changed
Events	                  event_name_1, event_type_1, event_name_2, event_type_2, is_event

We'll leave SNAP out of this first feature list until we decide how to handle it in a way that generalizes beyond California.because in sample we only have state_id -CA

In [119]:
df.columns.tolist()

['id',
 'item_id',
 'dept_id',
 'cat_id',
 'store_id',
 'state_id',
 'd',
 'sales',
 'date',
 'wm_yr_wk',
 'weekday',
 'wday',
 'month',
 'year',
 'event_name_1',
 'event_type_1',
 'event_name_2',
 'event_type_2',
 'snap_CA',
 'snap_TX',
 'snap_WI',
 'sell_price',
 'day_of_week',
 'is_weekend',
 'sales_lag_1',
 'sales_lag_7',
 'sales_lag_28',
 'rolling_mean_7',
 'rolling_mean_28',
 'price_available',
 'price_change',
 'price_changed',
 'is_event']

Our date column looks like this:
2011-01-29
2011-01-30
2011-01-31


It's useful information, but many scikit-learn models cannot use a Pandas datetime column directly as a numerical feature. We usually extract meaningful information from it.
Date-derived feature	What it helps capture
year	Long-term changes over time
month	Monthly and seasonal patterns
day_of_week	Weekly demand patterns
day_of_year	Position within the annual cycle
days_since_start	Overall time trend
We already created year, month, day_of_week, and is_weekend. So we're not ignoring dates; we're already using some of their information.

# Target and Feature Definition

In [120]:
target_col = "sales"
feature_cols = [
    # Product information
    "item_id",
    "dept_id",
    "cat_id",
    "store_id",
    "state_id",

    # Time features
    "year",
    "month",
    "day_of_week",
    "is_weekend",

    # Historical demand
    "sales_lag_1",
    "sales_lag_7",
    "sales_lag_28",
    "rolling_mean_7",
    "rolling_mean_28",

    # Price features
    "sell_price",
    "price_available",
    "price_change",
    "price_changed",

    # Event features
    "event_name_1",
    "event_type_1",
    "event_name_2",
    "event_type_2",
    "is_event"
]

missing_features = [
    col for col in feature_cols
    if col not in df.columns
]
print("Target:", target_col)
print("Number of input features:", len(feature_cols))
print("Missing features:", missing_features)

Target: sales
Number of input features: 23
Missing features: []

# Check missing values before modeling
Some missing values are expected in our dataset:
- sales_lag_28 and rolling_mean_28: the earliest observations in each product-store series don't have enough history.
- sell_price: some observations have no recorded price.
- price_change: unavailable when the current or previous price cannot be compared.
- Event columns: NaN generally means no event is recorded in that event slot.

In [121]:
# Missing values in input features
missing_counts = (
    df[feature_cols]
    .isna()
    .sum()
    .sort_values(ascending=False)
)

print("Missing values in input features:")
print(missing_counts[missing_counts > 0])

# Missing values in the target
print("\nMissing target values:", df[target_col].isna().sum())

Missing values in input features:
event_type_2       1909000
event_name_2       1909000
event_type_1       1759000
event_name_1       1759000
price_change        393504
sell_price          392504
sales_lag_28         28000
rolling_mean_28      28000
sales_lag_7           7000
rolling_mean_7        7000
sales_lag_1           1000
dtype: int64

Missing target values: 0

Our target, sales, has zero missing values, which is good.
Remember, a missing event means no event is recorded in that slot; a missing price means we have no matching price record. They are not the same problem.

Important: Let's check price_changed
There's a subtle issue we should correct before modeling.
Previously, we created price_changed from price_change. If we compared a missing price change against zero directly, Pandas could mark it as changed because NaN != 0 evaluates to True.
Your output doesn't show any missing values in price_changed, even though price_change has 393,504 missing values. This is a warning sign.

In [122]:
df["price_changed"] = pd.Series(
    pd.NA,
    index=df.index,
    dtype="Int8"
)
valid_price_change = df["price_change"].notna()

df.loc[valid_price_change, "price_changed"] = (
    df.loc[valid_price_change, "price_change"]
    .ne(0)
    .astype("int8")
)

In [123]:
print(df["price_changed"].value_counts(dropna=False))
print(
    "Missing price_changed:",
    df["price_changed"].isna().sum()
)
#The counts add up to 1,913,000, so no observations have disappeared.

price_changed
0       1518028
<NA>     393504
1          1468
Name: count, dtype: Int64
Missing price_changed: 393504

# Prepare the training and validation datasets

Time-based-splitting :
We must not randomly shuffle our time-series observations. Instead, we'll train on earlier dates and evaluate on later dates to simulate forecasting future demand.

Our validation strategy
80% — Train

20%- 

Earlier dates → model training. Later dates → validation on unseen future observations.

- 1. Remove observations without sufficient sales history
Our lag and rolling features require historical observations. The first 28 days of each product-store series do not have a complete 28-day history.
For this initial baseline, we'll exclude those rows. We will not drop rows merely because their price or event fields are missing.

In [124]:
history_cols = [
    "sales_lag_1",
    "sales_lag_7",
    "sales_lag_28",
    "rolling_mean_7",
    "rolling_mean_28"
]
df_model = df.dropna(subset=history_cols).copy()

print("Original shape:", df.shape)
print("Modeling shape:", df_model.shape)

Original shape: (1913000, 33)
Modeling shape: (1885000, 33)

In [125]:
df_model.columns.tolist()

['id',
 'item_id',
 'dept_id',
 'cat_id',
 'store_id',
 'state_id',
 'd',
 'sales',
 'date',
 'wm_yr_wk',
 'weekday',
 'wday',
 'month',
 'year',
 'event_name_1',
 'event_type_1',
 'event_name_2',
 'event_type_2',
 'snap_CA',
 'snap_TX',
 'snap_WI',
 'sell_price',
 'day_of_week',
 'is_weekend',
 'sales_lag_1',
 'sales_lag_7',
 'sales_lag_28',
 'rolling_mean_7',
 'rolling_mean_28',
 'price_available',
 'price_change',
 'price_changed',
 'is_event']

# Split chronologically

In [126]:
import numpy as np
import pandas as pd

# 1. Get the eligible dates in chronological order
unique_dates = np.sort(df_model["date"].unique())

# 2. Calculate the 80/20 cutoff
split_idx = int(len(unique_dates) * 0.8)
split_date = pd.Timestamp(unique_dates[split_idx])

# 3. Split rows by date
train_df = df_model[
    df_model["date"] < split_date
].copy()
valid_df = df_model[
    df_model["date"] >= split_date
].copy()
# 4. Select input features and target
X_train = train_df[feature_cols]
y_train = train_df[target_col]

X_valid = valid_df[feature_cols]
y_valid = valid_df[target_col]

# 5. Check the results
print("Cutoff date:", split_date)

print("\nX_train:", X_train.shape)
print("y_train:", y_train.shape)

print("\nX_valid:", X_valid.shape)
print("y_valid:", y_valid.shape)

print("\nTotal rows preserved:",
      len(train_df) + len(valid_df) == len(df_model))

print("Chronological split valid:",
      train_df["date"].max() < valid_df["date"].min())

print("Feature count correct:",
      X_train.shape[1] == len(feature_cols)
      and X_valid.shape[1] == len(feature_cols))

Cutoff date: 2015-04-14 00:00:00

X_train: (1508000, 23)
y_train: (1508000,)

X_valid: (377000, 23)
y_valid: (377000,)

Total rows preserved: True
Chronological split valid: True
Feature count correct: True

## What does chronologically mean?
Chronologically means arranging data in time order, from oldest to newest.
For our project, the dates start in January 2011 and continue until April 2016.
For example:
Date	Sales	Purpose
Jan 29, 2011	0	Training
Jan 30, 2011	2	Training
Jan 31, 2011	1	Training
...	...	...
Early April 2015	3	Around the split
...	...	...
April 24, 2016	4	Validation

Why do we split this way?
Imagine you're building a model today to predict tomorrow's demand.
You can use past data to learn patterns, but you cannot use tomorrow's actual sales to train the model before predicting them.
So our approach is:
Training data — Earlier dates
Approximately 80% of the dates. The model learns from historical demand patterns.

Train the model

Validation data — Later dates
Approximately 20% of the dates. We test how well the trained model predicts demand in a later period.

# Separate numerical and categorical features

ML model genetally requires categorical information to be represented numerically
month = 2 is already numeric
sell_price = 8.26 is numeric.
item_id = "HOBBIES_1_001" is categorical.
event_type_1 = "Cultural" is categorical. Dont do Cultutral ->1 we will perform Onehot encoding

In [127]:
# Categorical features
categorical_features = [
    "item_id",
    "dept_id",
    "cat_id",
    "store_id",
    "state_id",
    "event_name_1",
    "event_type_1",
    "event_name_2",
    "event_type_2"
]
# Numerical features
numeric_features = [
    col for col in feature_cols
    if col not in categorical_features
]
print("Categorical features:", len(categorical_features))
print(categorical_features)

print("\nNumerical features:", len(numeric_features))
print(numeric_features)

Categorical features: 9
['item_id', 'dept_id', 'cat_id', 'store_id', 'state_id', 'event_name_1', 'event_type_1', 'event_name_2', 'event_type_2']

Numerical features: 14
['year', 'month', 'day_of_week', 'is_weekend', 'sales_lag_1', 'sales_lag_7', 'sales_lag_28', 'rolling_mean_7', 'rolling_mean_28', 'sell_price', 'price_available', 'price_change', 'price_changed', 'is_event']

In [139]:
# Standardize missing event categories
# # Our intended representation for an unrecorded event is "No event".
# Work on independent copies
X_train = X_train.copy()
X_valid = X_valid.copy()
event_categorical_features = [
    "event_name_1",
    "event_type_1",
    "event_name_2",
    "event_type_2"
]
for col in event_categorical_features:
    X_train[col] = (
        X_train[col]
        .astype(object)
        .where(X_train[col].notna(), "No event")
    )

    X_valid[col] = (
        X_valid[col]
        .astype(object)
        .where(X_valid[col].notna(), "No event")
    )

In [140]:
print("Missing training event values:")
print(X_train[event_categorical_features].isna().sum())

print("\nMissing validation event values:")
print(X_valid[event_categorical_features].isna().sum())

Missing training event values:
event_name_1    0
event_type_1    0
event_name_2    0
event_type_2    0
dtype: int64

Missing validation event values:
event_name_1    0
event_type_1    0
event_name_2    0
event_type_2    0
dtype: int64

In [141]:
# Inspect the categorical columns
X_train[categorical_features].nunique(dropna=False).sort_values(
    ascending=False
)

item_id         1000
event_name_1      31
event_type_1       5
event_name_2       5
dept_id            3
event_type_2       3
cat_id             2
store_id           1
state_id           1
dtype: int64

- item_id has 1,000 distinct products. One-Hot Encoding it creates many columns, so we'll use sparse output to manage memory.


- store_id and state_id each have only one value in our California-only sample. They won't help distinguish observations in this sample, but we'll retain them in the pipeline so we can later support multiple stores and states.



- dropna=False counts missing values as distinct values. That's why our event-column counts include missing entries.

Why are we checking this? One-Hot Encoding creates additional columns for categories. A feature with many unique values, such as item_id, creates more columns than a feature with just a few values, such as state_id.

One detail specific to our project: state_id contains only CA in our current sample, so the model cannot learn differences between states yet.

Preprocessing: Preparing raw features so that a machine-learning model can use them.
Our next preprocessing steps will be:
1. Handle missing numerical values using an imputation strategy.
2. Handle missing categorical values meaningfully.
3. One-Hot Encode the categorical features.
4. Fit all preprocessing on training data only, then apply it to validation.

# Build the preprocess pipeline
We'll handle each feature group differently:
Feature group	        Treatment
Numerical	            Fill missing values using the training-set median
Product/store categories	Fill missing categories with "Unknown", then One-Hot Encode
Event categories	    Fill missing event slots with "No event", then One-Hot Encode
Important: We'll fit preprocessing on X_train only. Validation data must not influence the medians or the categories learned by the encoders.

In [142]:
product_categorical_features = [
    "item_id",
    "dept_id",
    "cat_id",
    "store_id",
    "state_id"
]
event_categorical_features = [
    "event_name_1",
    "event_type_1",
    "event_name_2",
    "event_type_2"
]

# Creating the preprocessing pipeline

In [157]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder,StandardScaler
# Numerical features
numeric_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(
        strategy="median",
        add_indicator=True
    )),
     (
        "scaler",
        StandardScaler()
    )
])
# Product and store categories
product_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(
        strategy="constant",
        fill_value="Unknown"
    )),
    ("onehot", OneHotEncoder(
        handle_unknown="ignore",
        sparse_output=True
    ))])
# Event categories
event_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(
        strategy="constant",
        fill_value="No event"
    )),
    ("onehot", OneHotEncoder(
        handle_unknown="ignore",
        sparse_output=True
    ))])

In [158]:
# Combine the transformations
preprocessor = ColumnTransformer(
    transformers=[
        ("numeric", numeric_transformer, numeric_features),
        ("product",product_transformer,product_categorical_features
        ),
        (
            "events",
            event_transformer,
            event_categorical_features
        )
    ],
    remainder="drop",
    sparse_threshold=0.3
)
preprocessor

ColumnTransformer(transformers=[('numeric',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(add_indicator=True,
                                                                strategy='median')),
                                                 ('scaler', StandardScaler())]),
                                 ['year', 'month', 'day_of_week', 'is_weekend',
                                  'sales_lag_1', 'sales_lag_7', 'sales_lag_28',
                                  'rolling_mean_7', 'rolling_mean_28',
                                  'sell_price', 'price_available',
                                  'price_change', 'price_changed',
                                  'is_event']),
                                (...
                                                  SimpleImputer(fill_value='Unknown',
                                                                strategy='constant')),
                                                 ('onehot',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['item_id', 'dept_id', 'cat_id', 'store_id',
                                  'state_id']),
                                ('events',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(fill_value='No '
                                                                           'event',
                                                                strategy='constant')),
                                                 ('onehot',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['event_name_1', 'event_type_1',
                                  'event_name_2', 'event_type_2'])])

# Fit preprocessing using training data only

In [159]:
# Use consistent numerical data types
X_train = X_train.copy()
X_valid = X_valid.copy()
X_train[numeric_features] = (
    X_train[numeric_features].astype("float64")
)
X_valid[numeric_features] = (
    X_valid[numeric_features].astype("float64")
)
# Learn imputation values and categories from training data
preprocessor.fit(X_train)

feature_names = preprocessor.get_feature_names_out()

print("Original input features:", len(feature_cols))
print("Transformed feature count:", len(feature_names))
print("Sample transformed feature names:")
print(feature_names[:20])

Original input features: 23
Transformed feature count: 1068
Sample transformed feature names:
['numeric__year' 'numeric__month' 'numeric__day_of_week'
 'numeric__is_weekend' 'numeric__sales_lag_1' 'numeric__sales_lag_7'
 'numeric__sales_lag_28' 'numeric__rolling_mean_7'
 'numeric__rolling_mean_28' 'numeric__sell_price'
 'numeric__price_available' 'numeric__price_change'
 'numeric__price_changed' 'numeric__is_event'
 'numeric__missingindicator_sell_price'
 'numeric__missingindicator_price_change'
 'numeric__missingindicator_price_changed'
 'product__item_id_HOBBIES_1_001' 'product__item_id_HOBBIES_1_002'
 'product__item_id_HOBBIES_1_003']

One-Hot Encoding: Converts categorical values into binary indicator columns without imposing an artificial numerical order.
Missing-value indicator: An additional feature that records whether an original value was missing.
fit() versus transform(): Our preprocessor learns medians and category vocabularies from X_train, then applies the same rules to training and validation data.

Most important takeaway: A model's input feature count does not have to equal the number of columns in the original dataset. Preprocessing can expand the feature space while preserving the number of observations.

In [160]:
import pandas as pd
from scipy import sparse

# Transform only 10 training rows
sample_transformed = preprocessor.transform(
    X_train.head(10)
)

# Convert this small sample to a dense array for easy viewing
if sparse.issparse(sample_transformed):
    sample_transformed = sample_transformed.toarray()

# Create a readable DataFrame
sample_df = pd.DataFrame(
    sample_transformed,
    columns=preprocessor.get_feature_names_out()
)

sample_df.head()

,numeric__year,numeric__month,numeric__day_of_week,numeric__is_weekend,numeric__sales_lag_1,numeric__sales_lag_7,numeric__sales_lag_28,numeric__rolling_mean_7,numeric__rolling_mean_28,numeric__sell_price,...,events__event_type_1_Religious,events__event_type_1_Sporting,events__event_name_2_Cinco De Mayo,events__event_name_2_Easter,events__event_name_2_Father's day,events__event_name_2_No event,events__event_name_2_OrthodoxEaster,events__event_type_2_Cultural,events__event_type_2_No event,events__event_type_2_Religious
0,-1.408167,-1.283225,0.998510,1.578208,-0.345376,-0.344171,-0.341056,-0.483568,-0.516879,-0.241391,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
1,-1.408167,-1.283225,1.498096,1.578208,-0.345376,-0.344171,-0.341056,-0.483568,-0.516879,-0.241391,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
2,-1.408167,-1.283225,-1.499421,-0.633630,-0.345376,-0.344171,-0.341056,-0.483568,-0.516879,-0.241391,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
3,-1.408167,-0.992887,-0.999835,-0.633630,-0.345376,-0.344171,-0.341056,-0.483568,-0.516879,-0.241391,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
4,-1.408167,-0.992887,-0.500249,-0.633630,-0.345376,-0.344171,-0.341056,-0.483568,-0.516879,-0.241391,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0

In [161]:
print("Shape:", sample_df.shape)

print("\nFirst 20 transformed columns:")
print(sample_df.columns[:20].tolist())

print("\nFirst 5 rows:")
display(sample_df.head())

Shape: (10, 1068)

First 20 transformed columns:
['numeric__year', 'numeric__month', 'numeric__day_of_week', 'numeric__is_weekend', 'numeric__sales_lag_1', 'numeric__sales_lag_7', 'numeric__sales_lag_28', 'numeric__rolling_mean_7', 'numeric__rolling_mean_28', 'numeric__sell_price', 'numeric__price_available', 'numeric__price_change', 'numeric__price_changed', 'numeric__is_event', 'numeric__missingindicator_sell_price', 'numeric__missingindicator_price_change', 'numeric__missingindicator_price_changed', 'product__item_id_HOBBIES_1_001', 'product__item_id_HOBBIES_1_002', 'product__item_id_HOBBIES_1_003']

First 5 rows:

,numeric__year,numeric__month,numeric__day_of_week,numeric__is_weekend,numeric__sales_lag_1,numeric__sales_lag_7,numeric__sales_lag_28,numeric__rolling_mean_7,numeric__rolling_mean_28,numeric__sell_price,...,events__event_type_1_Religious,events__event_type_1_Sporting,events__event_name_2_Cinco De Mayo,events__event_name_2_Easter,events__event_name_2_Father's day,events__event_name_2_No event,events__event_name_2_OrthodoxEaster,events__event_type_2_Cultural,events__event_type_2_No event,events__event_type_2_Religious
0,-1.408167,-1.283225,0.998510,1.578208,-0.345376,-0.344171,-0.341056,-0.483568,-0.516879,-0.241391,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
1,-1.408167,-1.283225,1.498096,1.578208,-0.345376,-0.344171,-0.341056,-0.483568,-0.516879,-0.241391,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
2,-1.408167,-1.283225,-1.499421,-0.633630,-0.345376,-0.344171,-0.341056,-0.483568,-0.516879,-0.241391,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
3,-1.408167,-0.992887,-0.999835,-0.633630,-0.345376,-0.344171,-0.341056,-0.483568,-0.516879,-0.241391,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
4,-1.408167,-0.992887,-0.500249,-0.633630,-0.345376,-0.344171,-0.341056,-0.483568,-0.516879,-0.241391,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0

In [162]:
for col in event_categorical_features:
    literal_none = X_train[col].map(
        lambda value: isinstance(value, str) and value == "None"
    ).sum()

    print(f"\n{col}")
    print("Actual missing values:", X_train[col].isna().sum())
    print("Literal 'None' strings:", literal_none)

event_name_1
Actual missing values: 0
Literal 'None' strings: 0

event_type_1
Actual missing values: 0
Literal 'None' strings: 0

event_name_2
Actual missing values: 0
Literal 'None' strings: 0

event_type_2
Actual missing values: 0
Literal 'None' strings: 0

In [163]:
print("Training event missing values:")
print(X_train[event_categorical_features].isna().sum())

print("\nValidation event missing values:")
print(X_valid[event_categorical_features].isna().sum())

Training event missing values:
event_name_1    0
event_type_1    0
event_name_2    0
event_type_2    0
dtype: int64

Validation event missing values:
event_name_1    0
event_type_1    0
event_name_2    0
event_type_2    0
dtype: int64

In [164]:
# Transform the training data
from scipy import sparse

# Transform the training features
X_train_processed = preprocessor.transform(X_train)

print("Processed training shape:", X_train_processed.shape)
print("Output type:", type(X_train_processed))
print("Is sparse:", sparse.issparse(X_train_processed))

Processed training shape: (1508000, 1068)
Output type: <class 'scipy.sparse._csr.csr_matrix'>
Is sparse: True

In [165]:
#Transform validation data
# Transform validation data using the existing fitted preprocessor
X_valid_processed = preprocessor.transform(X_valid)
print("Validation shape:", X_valid_processed.shape)
print("Output type:", type(X_valid_processed))
print("Is sparse:", sparse.issparse(X_valid_processed))

print("\nTraining target shape:", y_train.shape)
print("Validation target shape:", y_valid.shape)

Validation shape: (377000, 1068)
Output type: <class 'scipy.sparse._csr.csr_matrix'>
Is sparse: True

Training target shape: (1508000,)
Validation target shape: (377000,)

Don't convert the entire matrix using .toarray() just to inspect it. That creates a dense array and could consume a lot of RAM on your laptop.
Part	Meaning
scipy	Python library providing scientific computing tools
sparse	Tools for storing data containing many zeros efficiently
csr	    Compressed Sparse Row, a storage format
csr_matrix	The actual matrix object holding our processed features

CSR (Compressed Sparse Row) is a sparse matrix format designed for efficient row-oriented storage and operations. It's particularly useful for datasets with many zero values, such as one-hot encoded categorical features.

# Establish our first baseline forecast
before training a machine-learning model, we need a baseline. Otherwise, we won't know whether our model actually improves forecasting.
We'll use weekly-naive forecasting.
What does that mean?
Retail demand often has a weekly pattern. For example, if a product sold 3 units last Monday, we can use those 3 units as our prediction for the same product on the following Monday.
Our existing feature sales_lag_7 already contains the previous week's sales for that product-store series.
So our baseline rule is:
\[
\widehat{sales}_t = sales_{t-7}
\]

This is a simple forecasting rule, not an ML model. It gives us a reference score to beat.

# Baseline Model — Weekly Naive Forecast

In [154]:
import numpy as np
from sklearn.metrics import mean_absolute_error, mean_squared_error

# Actual demand in the validation period
y_actual = y_valid.to_numpy(dtype=float)

# Predict using sales from 7 days earlier
y_pred_baseline = valid_df["sales_lag_7"].to_numpy(dtype=float)

# Evaluation metrics
mae = mean_absolute_error(y_actual, y_pred_baseline)

rmse = np.sqrt(
    mean_squared_error(y_actual, y_pred_baseline)
)

total_actual_sales = np.abs(y_actual).sum()

wape = (
    np.abs(y_actual - y_pred_baseline).sum()
    / total_actual_sales * 100
    if total_actual_sales > 0
    else np.nan
)

print("Weekly Naive Baseline Results")
print("-----------------------------")
print(f"MAE:  {mae:.4f}")
print(f"RMSE: {rmse:.4f}")
print(f"WAPE: {wape:.2f}%")

Weekly Naive Baseline Results
-----------------------------
MAE:  1.1761
RMSE: 2.7130
WAPE: 100.06%

A WAPE of 100% means the total absolute error equals the total actual demand. Our baseline is slightly worse than that.
My honest assessment: the weekly-naive baseline is weak. But that's precisely why we're establishing a baseline—to see whether a better forecasting approach can improve upon it.

dataset has many zero-sales observations. So let's compare the weekly-naive method against an extremely simple baseline: predict zero sales for every observation.
Why? If most observations have zero demand, a zero-prediction baseline can perform surprisingly well under certain metrics.

In [155]:
import numpy as np
from sklearn.metrics import mean_absolute_error, mean_squared_error
y_actual = y_valid.to_numpy(dtype=float)
# Predict zero units for every observation
y_pred_zero = np.zeros_like(y_actual)
mae_zero = mean_absolute_error(y_actual, y_pred_zero)
rmse_zero = np.sqrt(
    mean_squared_error(y_actual, y_pred_zero)
)
wape_zero = (
    np.abs(y_actual - y_pred_zero).sum()
    / np.abs(y_actual).sum()
    * 100
)
print("Zero-Demand Baseline")
print("--------------------")
print(f"MAE:  {mae_zero:.4f}")
print(f"RMSE: {rmse_zero:.4f}")
print(f"WAPE: {wape_zero:.2f}%")

Zero-Demand Baseline
--------------------
MAE:  1.1755
RMSE: 2.8951
WAPE: 100.00%

Neither baseline is particularly strong. Our goal is to train a model that learns from product identity, historical demand, prices and calendar events to improve upon them.

Now visualize first then move forward